export interface HelpSection {
  contentKey: string;
  icon: string;
  iconColor: string;
  id: string;
  subtitleKey: string;
  titleKey: string;
}

export const HELP_SECTIONS: HelpSection[] = [
  {
    id: 'getting-started',
    contentKey: 'HELP.CONTENT_GETTING_STARTED',
    icon: 'rocket_launch',
    iconColor: '#1976d2',
    subtitleKey: 'HELP.SECTION_GETTING_STARTED_SUB',
    titleKey: 'HELP.SECTION_GETTING_STARTED',
  },
  {
    id: 'dashboard',
    contentKey: 'HELP.CONTENT_DASHBOARD',
    icon: 'dashboard',
    iconColor: '#1976d2',
    subtitleKey: 'HELP.SECTION_DASHBOARD_SUB',
    titleKey: 'HELP.SECTION_DASHBOARD',
  },
  {
    id: 'location',
    contentKey: 'HELP.CONTENT_LOCATION',
    icon: 'my_location',
    iconColor: '#2196f3',
    subtitleKey: 'HELP.SECTION_LOCATION_SUB',
    titleKey: 'HELP.SECTION_LOCATION',
  },
  {
    id: 'areas',
    contentKey: 'HELP.CONTENT_AREAS',
    icon: 'map',
    iconColor: '#ff9800',
    subtitleKey: 'HELP.SECTION_AREAS_SUB',
    titleKey: 'HELP.SECTION_AREAS',
  },
  {
    id: 'geofences',
    contentKey: 'HELP.CONTENT_GEOFENCES',
    icon: 'draw',
    iconColor: '#2196f3',
    subtitleKey: 'HELP.SECTION_GEOFENCES_SUB',
    titleKey: 'HELP.SECTION_GEOFENCES',
  },
  {
    id: 'pokemon',
    contentKey: 'HELP.CONTENT_POKEMON',
    icon: 'catching_pokemon',
    iconColor: '#4caf50',
    subtitleKey: 'HELP.SECTION_POKEMON_SUB',
    titleKey: 'HELP.SECTION_POKEMON',
  },
  {
    id: 'other-alarms',
    contentKey: 'HELP.CONTENT_OTHER_ALARMS',
    icon: 'shield',
    iconColor: '#f44336',
    subtitleKey: 'HELP.SECTION_OTHER_ALARMS_SUB',
    titleKey: 'HELP.SECTION_OTHER_ALARMS',
  },
  {
    id: 'delivery',
    contentKey: 'HELP.CONTENT_DELIVERY',
    icon: 'tune',
    iconColor: '#607d8b',
    subtitleKey: 'HELP.SECTION_DELIVERY_SUB',
    titleKey: 'HELP.SECTION_DELIVERY',
  },
  {
    id: 'test-alerts',
    contentKey: 'HELP.CONTENT_TEST_ALERTS',
    icon: 'send',
    iconColor: '#00897b',
    subtitleKey: 'HELP.SECTION_TEST_ALERTS_SUB',
    titleKey: 'HELP.SECTION_TEST_ALERTS',
  },
  {
    id: 'pokemon-availability',
    contentKey: 'HELP.CONTENT_POKEMON_AVAILABILITY',
    icon: 'visibility',
    iconColor: '#43a047',
    subtitleKey: 'HELP.SECTION_POKEMON_AVAILABILITY_SUB',
    titleKey: 'HELP.SECTION_POKEMON_AVAILABILITY',
  },
  {
    id: 'bulk',
    contentKey: 'HELP.CONTENT_BULK',
    icon: 'checklist',
    iconColor: '#795548',
    subtitleKey: 'HELP.SECTION_BULK_SUB',
    titleKey: 'HELP.SECTION_BULK',
  },
  {
    id: 'quick-picks',
    contentKey: 'HELP.CONTENT_QUICK_PICKS',
    icon: 'bolt',
    iconColor: '#ff6f00',
    subtitleKey: 'HELP.SECTION_QUICK_PICKS_SUB',
    titleKey: 'HELP.SECTION_QUICK_PICKS',
  },
  {
    id: 'profiles',
    contentKey: 'HELP.CONTENT_PROFILES',
    icon: 'compare_arrows',
    iconColor: '#7c4dff',
    subtitleKey: 'HELP.SECTION_PROFILES_SUB',
    titleKey: 'HELP.SECTION_PROFILES',
  },
  {
    id: 'cleaning',
    contentKey: 'HELP.CONTENT_CLEANING',
    icon: 'cleaning_services',
    iconColor: '#795548',
    subtitleKey: 'HELP.SECTION_CLEANING_SUB',
    titleKey: 'HELP.SECTION_CLEANING',
  },
  {
    id: 'appearance',
    contentKey: 'HELP.CONTENT_APPEARANCE',
    icon: 'palette',
    iconColor: '#673ab7',
    subtitleKey: 'HELP.SECTION_APPEARANCE_SUB',
    titleKey: 'HELP.SECTION_APPEARANCE',
  },
  {
    id: 'alerts-logout',
    contentKey: 'HELP.CONTENT_ALERTS_LOGOUT',
    icon: 'notifications',
    iconColor: '#ff5722',
    subtitleKey: 'HELP.SECTION_ALERTS_LOGOUT_SUB',
    titleKey: 'HELP.SECTION_ALERTS_LOGOUT',
  },
  {
    id: 'faq',
    contentKey: 'HELP.CONTENT_FAQ',
    icon: 'help_outline',
    iconColor: '#ff9800',
    subtitleKey: 'HELP.SECTION_FAQ_SUB',
    titleKey: 'HELP.SECTION_FAQ',
  },
];
