const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, 'src/assets/i18n');
const en = JSON.parse(fs.readFileSync(path.join(i18nDir, 'en.json'), 'utf8'));

// Translation maps for missing keys per language
const newTranslations = {
  de: {
    'DASHBOARD.WEATHER_1_MIN_AGO': 'Vor 1 Min.',
    'DASHBOARD.WEATHER_1_HR_AGO': 'Vor 1 Std.',
    'DASHBOARD.WEATHER_HRS_AGO': 'Vor {{count}} Std.',
    'DASHBOARD.SWITCH_PROFILE_SUCCESS': 'Gewechselt zu "{{name}}"',
    'DASHBOARD.SWITCH_PROFILE_FAILED': 'Profilwechsel fehlgeschlagen',
    'ONBOARDING.ARIA_LABEL': 'Willkommen Onboarding',
    'POKEMON.ADD_POKEMON': 'Pokemon hinzufügen',
    'POKEMON.LABEL_FORM_ID': 'Form-ID',
    'POKEMON.FILTER_IV_CP_LEVEL': 'IV / CP / Level',
    'POKEMON.FILTER_STATS_SECTION': 'Werte',
    'POKEMON.PVP_NONE_EDIT': 'Keine',
    'POKEMON.PVP_LITTLE_CUP_SHORT': 'Little Cup (500)',
    'POKEMON.PVP_GREAT_LEAGUE_SHORT': 'Superliga (1500)',
    'POKEMON.PVP_ULTRA_LEAGUE_SHORT': 'Hyperliga (2500)',
    'POKEMON.PVP_LEAGUE_SUFFIX': 'Liga',
    'POKEMON.PVP_RANK_RANGE': 'Rang {{best}}-{{worst}}',
    'POKEMON.PVP_BEST_RANK_HINT': 'z.B. 1',
    'POKEMON.PVP_WORST_RANK_HINT': 'z.B. 100',
    'ALARM.TAB_DELIVERY': 'Zustellung',
    'ALARM.COMMON_SETTINGS': 'Allgemeine Einstellungen',
    'RAIDS.LEVEL_MEGA': 'Mega',
    'RAIDS.ALL_RAIDS': 'Alle Raids',
    'RAIDS.ALL_LEVEL_RAIDS': 'Alle {{level}}-Raids',
    'RAIDS.RAID_SUFFIX': 'Raid',
    'RAIDS.RAID_BOSS_NUM': 'Raid-Boss #{{id}}',
    'RAIDS.POKEMON_SELECTED': '{{count}} Pokemon ausgewählt',
    'RAIDS.CLEAN_TAG': 'aufräumen',
    'RAIDS.CLEAN_TOOLTIP': 'Wird nach Ablauf automatisch gelöscht',
    'RAIDS.SNACK_CREATED_COUNT': '{{count}} Alarm(e) erstellt',
    'RAIDS.SNACK_BULK_DELETED': '{{count}} Alarme gelöscht',
    'RAIDS.SNACK_BULK_DISTANCE': 'Entfernung für {{count}} Alarme aktualisiert',
    'RAIDS.SNACK_ALL_DISTANCE': 'Alle Entfernungen aktualisiert',
    'RAIDS.SNACK_DELETED_ALL': 'Alle Raid- & Ei-Alarme gelöscht',
    'RAIDS.SNACK_FAILED_DELETE_ALL': 'Alarme konnten nicht gelöscht werden',
    'RAIDS.SNACK_FAILED_DISTANCE': 'Entfernungen konnten nicht aktualisiert werden',
    'RAIDS.CONFIRM_DELETE_RAID_TITLE': 'Raid-Alarm löschen',
    'RAIDS.CONFIRM_DELETE_RAID_MSG': 'Möchtest du den Alarm für {{name}} wirklich löschen?',
    'RAIDS.CONFIRM_DELETE_EGG_TITLE': 'Ei-Alarm löschen',
    'RAIDS.CONFIRM_DELETE_EGG_MSG': 'Möchtest du den {{name}}-Ei-Alarm wirklich löschen?',
    'RAIDS.CONFIRM_DELETE_ALL_TITLE': 'Alle Raid- & Ei-Alarme löschen',
    'RAIDS.CONFIRM_DELETE_ALL_MSG': 'Möchtest du wirklich ALLE Raid- und Ei-Alarme löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'RAIDS.CONFIRM_BULK_DELETE_TITLE': 'Ausgewählte Alarme löschen',
    'RAIDS.CONFIRM_BULK_DELETE_MSG': 'Möchtest du wirklich {{count}} Alarme löschen?',
    'RAIDS.CONFIRM_DELETE_SELECTED': 'Ausgewählte löschen',
    'QUESTS.TAB_SETTINGS': 'Einstellungen',
    'QUESTS.CLEAN_TAG': 'aufräumen',
    'QUESTS.CLEAN_TOOLTIP': 'Wird nach Ablauf automatisch gelöscht',
    'QUESTS.SELECTION_COUNT': '{{count}} ausgewählt',
    'QUESTS.ANY_POKEMON_ENCOUNTER': 'Beliebige Pokemon-Begegnung',
    'QUESTS.MEGA_ENERGY_SUFFIX': 'Mega-Energie',
    'QUESTS.CANDY_SUFFIX': 'Bonbons',
    'QUESTS.STARDUST': 'Sternenstaub',
    'QUESTS.STARDUST_AMOUNT': '{{amount}} Sternenstaub',
    'QUESTS.REWARD_POKEMON': 'Pokemon',
    'QUESTS.REWARD_ITEM': 'Item',
    'QUESTS.REWARD_MEGA_ENERGY': 'Mega-Energie',
    'QUESTS.REWARD_CANDY': 'Bonbons',
    'QUESTS.REWARD_TYPE_PREFIX': 'Quest-Typ:',
    'QUESTS.REWARD_POKEMON_ENCOUNTER': 'Pokemon-Begegnung',
    'QUESTS.CONFIRM_DELETE_TITLE': 'Quest-Alarm löschen',
    'QUESTS.CONFIRM_DELETE_MSG': 'Möchtest du diesen Quest-Alarm wirklich löschen?',
    'QUESTS.CONFIRM_DELETE_ALL_TITLE': 'Alle Quest-Alarme löschen',
    'QUESTS.CONFIRM_DELETE_ALL_MSG': 'Möchtest du wirklich ALLE Quest-Alarme löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'QUESTS.CONFIRM_BULK_DELETE_TITLE': 'Ausgewählte Alarme löschen',
    'QUESTS.CONFIRM_BULK_DELETE_MSG': 'Möchtest du wirklich {{count}} Alarme löschen?',
    'QUESTS.SNACK_CREATED_COUNT': '{{count}} Quest-Alarm(e) erstellt',
    'QUESTS.SNACK_BULK_DELETED': '{{count}} Alarme gelöscht',
    'QUESTS.SNACK_BULK_DISTANCE': 'Entfernung für {{count}} Alarme aktualisiert',
    'QUESTS.SNACK_ALL_DISTANCE': 'Alle Entfernungen aktualisiert',
    'QUESTS.SNACK_DELETED_ALL': 'Alle Quest-Alarme gelöscht',
    'QUESTS.SNACK_FAILED_DELETE_ALL': 'Alarme konnten nicht gelöscht werden',
    'QUESTS.SNACK_FAILED_DISTANCE': 'Entfernungen konnten nicht aktualisiert werden',
    'INVASIONS.CLEAN_TAG': 'aufräumen',
    'INVASIONS.CLEAN_TOOLTIP': 'Wird nach Ablauf automatisch gelöscht',
    'INVASIONS.POKESTOP_EVENT': 'PokéStop-Event',
    'INVASIONS.GENDER_ANY_LABEL': 'Beliebiges Geschlecht',
    'INVASIONS.GENDER_LABEL': 'Geschlecht',
    'INVASIONS.TAB_SETTINGS': 'Einstellungen',
    'INVASIONS.GENDER_FILTER_NA': 'Geschlechtsfilter gilt nicht für PokéStop-Events.',
    'INVASIONS.UNKNOWN_GRUNT': 'Unbekannter Rüpel',
    'INVASIONS.SNACK_ALL_CREATED': 'Alarm für alle Invasionen erstellt',
    'INVASIONS.SNACK_CREATED_COUNT': '{{count}} Invasions-Alarm(e) erstellt',
    'INVASIONS.CONFIRM_DELETE_TITLE': 'Invasions-Alarm löschen',
    'INVASIONS.CONFIRM_DELETE_MSG': 'Möchtest du diesen Invasions-Alarm wirklich löschen?',
    'INVASIONS.CONFIRM_DELETE_ALL_TITLE': 'Alle Invasions-Alarme löschen',
    'INVASIONS.CONFIRM_DELETE_ALL_MSG': 'Möchtest du wirklich ALLE Invasions-Alarme löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'INVASIONS.CONFIRM_BULK_DELETE_TITLE': 'Ausgewählte Alarme löschen',
    'INVASIONS.CONFIRM_BULK_DELETE_MSG': 'Möchtest du wirklich {{count}} Alarme löschen?',
    'INVASIONS.SNACK_BULK_DELETED': '{{count}} Alarme gelöscht',
    'INVASIONS.SNACK_BULK_DISTANCE': 'Entfernung für {{count}} Alarme aktualisiert',
    'INVASIONS.SNACK_ALL_DISTANCE': 'Alle Entfernungen aktualisiert',
    'INVASIONS.SNACK_DELETED_ALL': 'Alle Invasions-Alarme gelöscht',
    'INVASIONS.SNACK_FAILED_DELETE_ALL': 'Alarme konnten nicht gelöscht werden',
    'INVASIONS.SNACK_FAILED_DISTANCE': 'Entfernungen konnten nicht aktualisiert werden',
    'AREAS.SEARCH_AREAS': 'Gebiete suchen',
    'PROFILES.SNACK_FAILED_UPDATE': 'Profil konnte nicht aktualisiert werden',
    'PROFILES.SNACK_UPDATED': 'Profil umbenannt in "{{name}}"',
    'PROFILES.SNACK_FAILED_SCHEDULE': 'Zeitplan konnte nicht aktualisiert werden',
    'PROFILES.SNACK_SCHEDULE_UPDATED': 'Zeitplan aktualisiert',
    'PROFILES.SNACK_EXPORTED': '"{{name}}" Backup exportiert',
    'PROFILES.SNACK_INVALID_BACKUP': 'Ungültiges Backup-Dateiformat',
    'PROFILES.SNACK_UNSUPPORTED_VERSION': 'Nicht unterstützte Backup-Version',
    'PROFILES.SNACK_FAILED_LOAD': 'Profilübersicht konnte nicht geladen werden',
    'PROFILES.CONFIRM_DELETE_TITLE': 'Profil löschen',
    'PROFILES.CONFIRM_DELETE_MSG': 'Möchtest du das Profil "{{name}}" (#{{number}}) wirklich löschen? Alle Alarme gehen verloren.',
    'PROFILES.DUPLICATE_DIALOG_TITLE': 'Profil duplizieren',
    'PROFILES.DUPLICATE': 'Duplizieren',
    'PROFILES.DUPLICATE_DESC': 'Erstelle ein neues Profil mit allen Alarmen von {{name}}.',
    'PROFILES.NEW_PROFILE_NAME': 'Neuer Profilname',
    'PROFILES.IMPORT_DIALOG_TITLE': 'Profil importieren',
    'PROFILES.IMPORT_DESC': 'Erstelle ein neues Profil mit allen Alarmen aus diesem Backup.',
    'PROFILES.PROFILE_NUMBER': 'Profilnummer',
    'PROFILES.SCHEDULE_TOOLTIP': 'Zeitplan für aktive Stunden bearbeiten',
    'PROFILES.ACTIVE_HOURS_TITLE': 'Aktive Stunden',
    'PROFILES.ACTIVE_HOURS_DAYS': 'Tage',
    'PROFILES.ACTIVE_HOURS_WEEKDAYS': 'Wochentage',
    'PROFILES.ACTIVE_HOURS_WEEKENDS': 'Wochenende',
    'PROFILES.ACTIVE_HOURS_EVERY_DAY': 'Jeden Tag',
    'PROFILES.ACTIVE_HOURS_TIME': 'Uhrzeit',
    'PROFILES.ACTIVE_HOURS_HOUR': 'Stunde',
    'PROFILES.ACTIVE_HOURS_MINUTE': 'Minute',
    'PROFILES.ACTIVE_HOURS_ADD': 'Hinzufügen',
    'PROFILES.ACTIVE_HOURS_ADD_TOOLTIP': 'Aktivierungsregel hinzufügen',
    'PROFILES.ACTIVE_HOURS_RULES': 'Regeln',
    'PROFILES.ACTIVE_HOURS_NO_RULES': 'Keine Aktivierungsregeln. Profil muss manuell gestartet werden.',
    'PROFILES.ACTIVE_HOURS_REMOVE_RULE': 'Regel entfernen',
    'PROFILES.ACTIVE_HOURS_WEEKLY_PREVIEW': 'Wochenvorschau',
    'PROFILES.ACTIVE_HOURS_CLEAR_ALL': 'Alle löschen',
    'GEOFENCES.CONFIRM_DELETE_TITLE': 'Eigene Geofence löschen',
    'GEOFENCES.CONFIRM_DELETE_MSG': 'Möchtest du "{{name}}" wirklich löschen?',
    'GEOFENCES.SNACK_FAILED_UPDATE': 'Geofence konnte nicht aktualisiert werden',
    'GEOFENCES.SNACK_UPDATED': 'Geofence aktualisiert',
    'GEOFENCES.SNACK_NO_EXPORT': 'Keine Geofences zum Exportieren',
    'GEOFENCES.SNACK_MIN_POINTS': 'Ein Geofence braucht mindestens 3 Punkte',
    'GEOFENCES.SNACK_IMPORTED': '{{count}} Geofence(s) importiert',
    'GEOFENCES.SUBMIT_CONFIRM_TITLE': 'Geofence zur öffentlichen Überprüfung einreichen',
    'GEOFENCES.SUBMIT_CONFIRM_TEXT': 'Zur Überprüfung einreichen',
    'GEOFENCES.SUBMIT_CONFIRM_MSG': '"{{name}}" wird zur Überprüfung an das Admin-Team gesendet.',
    'GEOFENCES.SNACK_FAILED_ACTIVATE': 'Geofence konnte nicht aktiviert werden',
    'GEOFENCES.SNACK_FAILED_DEACTIVATE': 'Geofence konnte nicht deaktiviert werden',
    'GEOFENCES.SNACK_EXPORTED': '{{count}} Geofence(s) exportiert',
    'GEOFENCES.NAME_DIALOG_TITLE': 'Geofence benennen',
    'GEOFENCES.NAME_LABEL': 'Geofence-Name',
    'GEOFENCES.NAME_PLACEHOLDER': 'z.B. Meine Parkroute',
    'GEOFENCES.NAME_WHITESPACE_ERROR': 'Name darf nicht nur Leerzeichen enthalten',
    'GEOFENCES.NAME_INVALID_CHARS_ERROR': 'Nur Buchstaben, Zahlen, Leerzeichen, Bindestriche, Apostrophe und Klammern erlaubt',
    'GEOFENCES.REGION_LABEL': 'Region',
    'GEOFENCES.CHANGE_REGION': 'Ändern',
    'GEOFENCES.SELECT_REGION': 'Region auswählen',
    'GEOFENCES.SEARCH_REGIONS': 'Regionen suchen...',
    'CLEANING.LABEL_EGGS': 'Eier',
    'QUICK_PICKS.SNACK_FAILED_LOAD': 'Schnellauswahl konnte nicht geladen werden',
    'QUICK_PICKS.CONFIRM_DELETE_TITLE': 'Schnellauswahl löschen',
    'QUICK_PICKS.CONFIRM_DELETE_MSG': '"{{name}}" endgültig löschen?',
    'QUICK_PICKS.SNACK_FAILED_DELETE': 'Löschen fehlgeschlagen',
    'QUICK_PICKS.SNACK_DELETED': 'Schnellauswahl gelöscht',
    'QUICK_PICKS.CONFIRM_REMOVE_TITLE': 'Schnellauswahl entfernen',
    'QUICK_PICKS.CONFIRM_REMOVE_MSG': '"{{name}}" entfernen? Dabei werden {{count}} Alarm(e) gelöscht.',
    'QUICK_PICKS.SNACK_FAILED_REMOVE': 'Entfernen fehlgeschlagen',
    'QUICK_PICKS.SNACK_REMOVED': 'Schnellauswahl entfernt -- {{count}} Alarm(e) gelöscht',
    'QUICK_PICKS.CONFIRM_RESET_MSG': 'Alle Admin-Schnellauswahlen werden gelöscht und die Standardwerte wiederhergestellt.',
    'QUICK_PICKS.SNACK_FAILED_RESET': 'Standardwerte konnten nicht wiederhergestellt werden',
    'QUICK_PICKS.SNACK_RESET': 'Standardwerte wiederhergestellt',
    'QUICK_PICKS.SNACK_FAILED_SAVE': 'Schnellauswahl konnte nicht gespeichert werden',
    'QUICK_PICKS.SNACK_UPDATED': 'Schnellauswahl aktualisiert',
    'QUICK_PICKS.SNACK_CREATED_QP': 'Schnellauswahl erstellt',
    'QUICK_PICKS.APPLY_STATUS_CREATING': '{{count}} einzelne Alarme werden erstellt...',
    'QUICK_PICKS.APPLY_STATUS_APPLYING': 'Schnellauswahl wird angewendet...',
    'QUICK_PICKS.SNACK_FAILED_APPLY': 'Schnellauswahl konnte nicht angewendet werden',
    'QUICK_PICKS.SNACK_APPLIED': 'Schnellauswahl angewendet: {{count}} Alarm(e) erstellt',
    'QUICK_PICKS.TAB_OPTIONS': 'Optionen',
    'QUICK_PICKS.EXCLUDE_POKEMON': 'Bestimmte Pokemon ausschließen',
    'QUICK_PICKS.EXCLUDE_HINT': 'Bestimmte Pokemon bei dieser Schnellauswahl überspringen.',
    'QUICK_PICKS.EXCLUDED_SUMMARY': '{{count}} Pokemon ausgeschlossen',
    'QUICK_PICKS.INDIVIDUAL_WARNING': 'Dies erstellt {{count}} einzelne Alarm-Einträge.',
    'QUICK_PICKS.NO_OPTIONS_HINT': 'Keine zusätzlichen Optionen. Wechsle zum Zustellungs-Tab.',
    'QUICK_PICKS.TAB_DELIVERY': 'Zustellung',
    'QUICK_PICKS.CLEAN_HINT': 'Löscht die Benachrichtigung automatisch nach Ablauf',
    'QUICK_PICKS.APPLYING': 'Wird angewendet...',
    'QUICK_PICKS.APPLY_WITH_COUNT': 'Anwenden ({{count}} Alarme)',
    'QUICK_PICKS.EDIT_DIALOG_TITLE': 'Schnellauswahl bearbeiten',
    'QUICK_PICKS.CREATE_DIALOG_TITLE': 'Schnellauswahl erstellen',
    'QUICK_PICKS.FIELD_NAME': 'Name',
    'QUICK_PICKS.FIELD_DESCRIPTION': 'Beschreibung',
    'QUICK_PICKS.FIELD_ICON': 'Symbol',
    'QUICK_PICKS.FIELD_CATEGORY': 'Kategorie',
    'QUICK_PICKS.FIELD_ALARM_TYPE': 'Alarmtyp',
    'QUICK_PICKS.FIELD_SORT_ORDER': 'Sortierung',
    'QUICK_PICKS.FILTER_SETTINGS': 'Filtereinstellungen',
    'QUICK_PICKS.FIELD_POKEMON_ID': 'Pokemon-ID',
    'QUICK_PICKS.FIELD_EXCLUSIVE': 'Exklusiv',
    'QUICK_PICKS.FIELD_REWARD_TYPE': 'Belohnungstyp',
    'QUICK_PICKS.FIELD_REWARD': 'Belohnung',
    'QUICK_PICKS.FIELD_SHINY': 'Shiny',
    'QUICK_PICKS.FIELD_GRUNT_TYPE': 'Rüpel-Typ',
    'QUICK_PICKS.FIELD_LURE_ID': 'Lockmodul-ID',
    'QUICK_PICKS.FIELD_MOVE': 'Attacke',
    'QUICK_PICKS.FIELD_EVOLUTION': 'Entwicklung',
    'AUTH.SITE_TITLE_DEFAULT': 'DM-Benachrichtigungen',
    'AUTH.AUTH_FAILED': 'Authentifizierung fehlgeschlagen',
    'AUTH.BACK_TO_LOGIN': 'Zurück zur Anmeldung',
    'AUTH.ERR_DISCORD_FETCH': 'Discord-Benutzerinformationen konnten nicht abgerufen werden.',
    'AUTH.ERR_MISSING_CODE': 'Kein Autorisierungscode von Discord erhalten.',
    'AUTH.ERR_TOKEN_EXCHANGE': 'Autorisierungscode konnte nicht mit Discord ausgetauscht werden.',
    'AUTH.ERR_NOT_REGISTERED': 'Dein Konto ist nicht in Poracle registriert.',
    'AUTH.ERR_GENERIC': 'Authentifizierungsfehler: {{error}}',
    'AUTH.ERR_NO_TOKEN': 'Kein Authentifizierungstoken erhalten.',
    'ADMIN.APPROVAL_DIALOG_TITLE': 'Geofence überprüfen',
    'ADMIN.APPROVAL_NAME': 'Name',
    'ADMIN.APPROVAL_GROUP': 'Gruppe',
    'ADMIN.APPROVAL_SUBMITTED': 'Eingereicht',
    'ADMIN.APPROVAL_APPROVE': 'Genehmigen',
    'ADMIN.APPROVAL_REJECT': 'Ablehnen',
    'ADMIN.APPROVAL_PROMOTED_NAME': 'Beförderter Name',
    'ADMIN.APPROVAL_PROMOTED_NAME_PLACEHOLDER': 'Name für die beförderte Geofence',
    'ADMIN.APPROVAL_PROMOTED_NAME_HINT': 'Optional. Standardmäßig der aktuelle Anzeigename.',
    'ADMIN.APPROVAL_REJECT_REASON': 'Ablehnungsgrund',
    'ADMIN.APPROVAL_REJECT_PLACEHOLDER': 'Erkläre, warum diese Geofence abgelehnt wird...',
    'ADMIN.USERS_DESC_FULL': 'Registrierte Discord-Benutzer verwalten. <strong>Gestoppt</strong> = Benutzer hat Alarme pausiert oder Ratenlimit erreicht. <strong>Gesperrt</strong> = vom Admin gesperrt.',
    'ADMIN.COLUMN_DISABLED_SINCE': 'Deaktiviert seit',
    'ADMIN.COLUMN_URL': 'URL',
    'ADMIN.COLUMN_DELEGATES': 'Stellvertreter',
    'ADMIN.COLUMN_OWNER': 'Besitzer',
    'ADMIN.COLUMN_REGION': 'Region',
    'ADMIN.COLUMN_POINTS': 'Punkte',
    'ADMIN.COLUMN_CREATED': 'Erstellt',
    'ADMIN.COLUMN_SUBMITTED': 'Eingereicht',
    'ADMIN.COLUMN_REVIEWED_BY': 'Überprüft von',
    'ADMIN.TRY_ADJUSTING_FILTERS': 'Versuche deine Filter anzupassen.',
    'ADMIN.NO_USERS_YET': 'Noch keine Benutzer registriert.',
    'ADMIN.CONFIRM_DELETE_ALARMS': 'Möchtest du wirklich ALLE Alarme für "{{name}}" löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'ADMIN.CONFIRM_DELETE_USER': 'Möchtest du "{{name}}" wirklich endgültig löschen?',
    'ADMIN.SNACK_FAILED_IMPERSONATE': 'Identitätswechsel fehlgeschlagen',
    'ADMIN.SNACK_FAILED_LOAD_USERS': 'Benutzer konnten nicht geladen werden',
    'ADMIN.WEBHOOKS_TITLE': 'Webhooks',
    'ADMIN.WEBHOOKS_DESC': 'Registrierte Webhook-Ziele verwalten.',
    'ADMIN.ADD_WEBHOOK': 'Webhook hinzufügen',
    'ADMIN.SEARCH_WEBHOOKS': 'Webhooks suchen',
    'ADMIN.FILTER_WEBHOOK_PLACEHOLDER': 'Nach Name oder URL filtern...',
    'ADMIN.CLICK_TO_COPY': 'Zum Kopieren klicken',
    'ADMIN.GLOBAL_ADMIN': 'Globaler Admin',
    'ADMIN.CONFIG_DELEGATE': 'Config-Stellvertreter',
    'ADMIN.BLOCK_WEBHOOK': 'Webhook sperren',
    'ADMIN.UNBLOCK_WEBHOOK': 'Webhook entsperren',
    'ADMIN.MANAGE_ALARMS': 'Alarme verwalten',
    'ADMIN.MANAGE_ALARMS_TOOLTIP': 'Alarme für diesen Webhook verwalten',
    'ADMIN.MANAGE_DELEGATES': 'Stellvertreter verwalten',
    'ADMIN.DELETE_WEBHOOK': 'Webhook löschen',
    'ADMIN.NO_WEBHOOKS': 'Keine Webhooks gefunden',
    'ADMIN.NO_WEBHOOKS_YET': 'Keine Webhooks registriert.',
    'ADMIN.CONFIRM_DELETE_WEBHOOK': 'Möchtest du "{{name}}" wirklich endgültig löschen?',
    'ADMIN.SNACK_FAILED_DELETE_WEBHOOK': 'Webhook konnte nicht gelöscht werden',
    'ADMIN.SNACK_WEBHOOK_DELETED': '"{{name}}" gelöscht',
    'ADMIN.SNACK_URL_COPIED': 'URL in die Zwischenablage kopiert',
    'ADMIN.SNACK_FAILED_LOAD_WEBHOOKS': 'Webhooks konnten nicht geladen werden',
    'ADMIN.SNACK_FAILED_SWITCH_WEBHOOK': 'Wechsel zum Webhook-Kontext fehlgeschlagen',
    'ADMIN.SNACK_FAILED_ADD_WEBHOOK': 'Webhook konnte nicht hinzugefügt werden',
    'ADMIN.SNACK_WEBHOOK_ADDED': 'Webhook "{{name}}" hinzugefügt',
    'ADMIN.SNACK_FAILED_ADD_DELEGATE': 'Stellvertreter konnte nicht hinzugefügt werden',
    'ADMIN.SNACK_FAILED_LOAD_DELEGATES': 'Stellvertreter konnten nicht geladen werden',
    'ADMIN.SNACK_FAILED_REMOVE_DELEGATE': 'Stellvertreter konnte nicht entfernt werden',
    'ADMIN.MANAGE_DELEGATES_TITLE': 'Stellvertreter verwalten',
    'ADMIN.DELEGATES_HINT': 'Stellvertreter können Alarme für diesen Webhook verwalten.',
    'ADMIN.GLOBAL_ADMIN_TOOLTIP': 'Globaler Admin (aus Poracle-Konfiguration)',
    'ADMIN.CONFIG_DELEGATE_TOOLTIP': 'Stellvertreter aus Poracle-Konfiguration (nur lesen)',
    'ADMIN.REMOVE_DELEGATE': 'Stellvertreter entfernen',
    'ADMIN.SEARCH_USER_LABEL': 'Benutzer nach Name oder ID suchen',
    'ADMIN.SEARCH_USER_PLACEHOLDER': 'Name oder Discord-Benutzer-ID...',
    'ADMIN.WEBHOOK_NAME': 'Name',
    'ADMIN.WEBHOOK_NAME_PLACEHOLDER': 'z.B. #pogo-alerts',
    'ADMIN.WEBHOOK_NAME_REQUIRED': 'Name ist erforderlich',
    'ADMIN.WEBHOOK_URL': 'Webhook-URL',
    'ADMIN.WEBHOOK_URL_PLACEHOLDER': 'https://discord.com/api/webhooks/...',
    'ADMIN.WEBHOOK_URL_REQUIRED': 'URL ist erforderlich',
    'ADMIN.WEBHOOK_URL_INVALID': 'Muss eine gültige https://-URL sein',
    'ADMIN.MY_WEBHOOKS_TITLE': 'Meine Webhooks',
    'ADMIN.MY_WEBHOOKS_DESC': 'Webhooks, für die du als Stellvertreter eingesetzt bist.',
    'ADMIN.NO_WEBHOOKS_ASSIGNED': 'Keine Webhooks zugewiesen',
    'ADMIN.NO_WEBHOOKS_ASSIGNED_DESC': 'Du wurdest keinem Webhook als Stellvertreter zugewiesen.',
    'ADMIN.GEOFENCES_TITLE': 'Benutzer-Geofences',
    'ADMIN.GEOFENCES_DESC': 'Einreichungen überprüfen, Benutzer-Geofences verwalten und Einträge bereinigen.',
    'ADMIN.GEO_STATUS_PENDING': 'Ausstehend',
    'ADMIN.GEO_STATUS_APPROVED': 'Genehmigt',
    'ADMIN.GEO_STATUS_REJECTED': 'Abgelehnt',
    'ADMIN.VIEW_CARD': 'Kartenansicht (nach Region gruppiert)',
    'ADMIN.VIEW_LIST': 'Listenansicht (nach Region gruppiert)',
    'ADMIN.VIEW_TABLE': 'Tabellenansicht (alle Geofences)',
    'ADMIN.VIEW_DETAILS': 'Details anzeigen',
    'ADMIN.VIEW_GEOFENCE_DETAILS': 'Geofence-Details anzeigen',
    'ADMIN.REVIEW': 'Überprüfen',
    'ADMIN.REVIEW_SUBMISSION': 'Einreichung überprüfen',
    'ADMIN.DELETE_GEOFENCE': 'Geofence löschen und bereinigen',
    'ADMIN.NO_POLYGON_DATA': 'Keine Polygon-Daten',
    'ADMIN.POINTS': 'Punkte',
    'ADMIN.CREATED': 'Erstellt',
    'ADMIN.SUBMITTED': 'Eingereicht',
    'ADMIN.REVIEWED_BY': 'Überprüft von',
    'ADMIN.PROMOTED_AS': 'Befördert als:',
    'ADMIN.NO_REGION': 'Keine Region',
    'ADMIN.NO_GEOFENCES': 'Keine Geofences',
    'ADMIN.NO_PENDING_SUBMISSIONS': 'Keine Einreichungen warten auf Überprüfung.',
    'ADMIN.NO_GEOFENCES_YET': 'Noch keine benutzerdefinierten Geofences vorhanden.',
    'ADMIN.NO_GEOFENCES_STATUS': 'Keine Geofences mit diesem Status.',
    'ADMIN.CONFIRM_DELETE_GEOFENCE': '"{{name}}" (Besitzer: {{owner}}) endgültig löschen?',
    'ADMIN.ADMIN_DELETE_GEOFENCE': 'Admin: Geofence löschen',
    'ADMIN.SNACK_FAILED_DELETE_GEOFENCE': 'Geofence konnte nicht gelöscht werden',
    'ADMIN.SNACK_GEOFENCE_DELETED': '"{{name}}" gelöscht',
    'ADMIN.SNACK_FAILED_LOAD_GEOFENCES': 'Geofences konnten nicht geladen werden',
    'ADMIN.SNACK_FAILED_APPROVE': 'Genehmigung fehlgeschlagen',
    'ADMIN.SNACK_APPROVED': '"{{name}}" genehmigt',
    'ADMIN.SNACK_FAILED_REJECT': 'Ablehnung fehlgeschlagen',
    'ADMIN.SNACK_REJECTED': '"{{name}}" abgelehnt',
    'ADMIN.SERVERS_TITLE': 'Poracle-Server',
    'ADMIN.SERVERS_DESC': 'Serverstatus überwachen und Poracle-Instanzen neustarten.',
    'ADMIN.REFRESH_STATUS': 'Serverstatus aktualisieren',
    'ADMIN.RESTART_ALL': 'Alle neustarten',
    'ADMIN.RESTART_ALL_TOOLTIP': 'Alle Poracle-Server neustarten',
    'ADMIN.RESTART_ALL_TITLE': 'Alle Poracle-Server neustarten',
    'ADMIN.CONFIRM_RESTART_ALL': 'Alle Poracle-Server werden neugestartet. Benutzer erhalten kurzzeitig keine Benachrichtigungen.',
    'ADMIN.RESTART': 'Neustarten',
    'ADMIN.RESTART_SERVER': 'Diesen Server neustarten',
    'ADMIN.RESTART_SERVER_TITLE': 'Poracle-Server neustarten',
    'ADMIN.CONFIRM_RESTART_SERVER': 'Möchtest du "{{name}}" ({{host}}) wirklich neustarten?',
    'ADMIN.SERVER_ONLINE': 'Online',
    'ADMIN.SERVER_OFFLINE': 'Offline',
    'ADMIN.CHECKED': 'Geprüft',
    'ADMIN.NO_SERVERS': 'Keine Poracle-Server gefunden',
    'ADMIN.NO_SERVERS_DESC': 'Keine Poracle-Server-Instanzen konfiguriert.',
    'ADMIN.SNACK_FAILED_RESTART_ALL': 'Server konnten nicht neugestartet werden',
    'ADMIN.SNACK_ALL_RESTARTED': 'Alle Server neugestartet',
    'ADMIN.SNACK_FAILED_RESTART': '"{{name}}" konnte nicht neugestartet werden',
    'ADMIN.SNACK_RESTARTED': '"{{name}}" neugestartet',
    'ADMIN.SNACK_FAILED_LOAD_SERVERS': 'Poracle-Server konnten nicht geladen werden',
    'DIALOG.LOCATION_SAVE_ERROR': 'Standort konnte nicht aktualisiert werden',
    'DIALOG.LOCATION_SAVE_SUCCESS': 'Standort erfolgreich aktualisiert',
    'DIALOG.LOCATION_GEO_UNSUPPORTED': 'Geolokalisierung wird von deinem Browser nicht unterstützt',
    'DIALOG.LOCATION_GEO_UNABLE': 'Standort konnte nicht ermittelt werden',
    'DIALOG.LOCATION_GEO_DENIED': 'Standortberechtigung verweigert',
    'POKEMON_SELECTOR.GEN': 'Gen',
    'POKEMON_SELECTOR.TYPE': 'Typ',
    'POKEMON_SELECTOR.LIVE': 'Live',
    'POKEMON_SELECTOR.SPAWNING': 'Spawnt',
    'POKEMON_SELECTOR.SPECIES_ACTIVE': '{{count}} Arten aktiv',
    'POKEMON_SELECTOR.SEARCH_LABEL': 'Pokemon suchen',
    'POKEMON_SELECTOR.SEARCH_HINT': 'Name oder ID eingeben...',
    'POKEMON_SELECTOR.CURRENTLY_SPAWNING': 'Aktuell spawnend',
    'TEMPLATE_SELECTOR.LABEL': 'Vorlage',
    'TEMPLATE_SELECTOR.DEFAULT': 'Standard',
    'TEMPLATE_SELECTOR.TEMPLATE_NUM': 'Vorlage {{num}}',
    'TEMPLATE_SELECTOR.HINT': 'Nachrichtenformat der Benachrichtigung',
    'TEMPLATE_SELECTOR.HIDE_OPTIONS': 'Optionen ausblenden',
    'TEMPLATE_SELECTOR.PREVIEW_OPTIONS': 'Vorschauoptionen',
    'TEMPLATE_SELECTOR.MAP_PREVIEW': 'Kartenvorschau',
    'REGION_SELECTOR.ALL_REGIONS': 'Alle Regionen',
    'GYM_PICKER.SEARCH_LABEL': 'Arena suchen (optional)',
    'GYM_PICKER.SEARCH_HINT': 'Arenaname eingeben...',
    'GYM_PICKER.CLEAR_ARIA': 'Arena-Auswahl löschen',
    'DELIVERY_PREVIEW.AREAS_LABEL': 'Benachrichtigungen werden für diese Gebiete gesendet:',
    'DELIVERY_PREVIEW.NO_AREAS': 'Keine Gebiete konfiguriert.',
    'DELIVERY_PREVIEW.SET_UP_AREAS': 'Gebiete einrichten',
    'DELIVERY_PREVIEW.FIRST': 'zuerst.',
    'DELIVERY_PREVIEW.DISTANCE_LABEL': 'Benachrichtigungen innerhalb von {{distance}} km um deinen Standort:',
    'DELIVERY_PREVIEW.MAP_ALT': 'Entfernungsradius-Karte',
    'LOCATION_WARNING.TEXT': 'Kein Standort gesetzt \u2014 Zeitplan verwendet möglicherweise falsche Zeitzone',
    'LOCATION_WARNING.TOOLTIP': 'Aktive Stunden verwenden den Profilstandort zur Zeitzonenbestimmung. Ohne gesetzten Standort kann der Zeitplan zur falschen Zeit aktiviert werden.',
    'ACTIVE_HOURS_CHIP.MANUAL_ONLY': 'Nur manuell',
    'ACTIVE_HOURS_CHIP.NO_SCHEDULE': 'Kein Zeitplan gesetzt \u2014 Profil läuft manuell oder immer',
    'ALARM_INFO.PING_TOOLTIP': 'Ping: {{ping}}'
  },
  fr: {
    'DASHBOARD.WEATHER_1_MIN_AGO': 'Il y a 1 min',
    'DASHBOARD.WEATHER_1_HR_AGO': 'Il y a 1 h',
    'DASHBOARD.WEATHER_HRS_AGO': 'Il y a {{count}} h',
    'DASHBOARD.SWITCH_PROFILE_SUCCESS': 'Basculé vers "{{name}}"',
    'DASHBOARD.SWITCH_PROFILE_FAILED': 'Échec du changement de profil',
    'ONBOARDING.ARIA_LABEL': 'Bienvenue onboarding',
    'POKEMON.ADD_POKEMON': 'Ajouter un Pokemon',
    'POKEMON.LABEL_FORM_ID': 'ID de forme',
    'POKEMON.FILTER_IV_CP_LEVEL': 'IV / CP / Niveau',
    'POKEMON.FILTER_STATS_SECTION': 'Stats',
    'POKEMON.PVP_NONE_EDIT': 'Aucune',
    'POKEMON.PVP_LITTLE_CUP_SHORT': 'Coupe Junior (500)',
    'POKEMON.PVP_GREAT_LEAGUE_SHORT': 'Ligue Super (1500)',
    'POKEMON.PVP_ULTRA_LEAGUE_SHORT': 'Ligue Hyper (2500)',
    'POKEMON.PVP_LEAGUE_SUFFIX': 'Ligue',
    'POKEMON.PVP_RANK_RANGE': 'Rang {{best}}-{{worst}}',
    'POKEMON.PVP_BEST_RANK_HINT': 'ex. 1',
    'POKEMON.PVP_WORST_RANK_HINT': 'ex. 100',
    'ALARM.TAB_DELIVERY': 'Livraison',
    'ALARM.COMMON_SETTINGS': 'Paramètres communs',
    'RAIDS.LEVEL_MEGA': 'Méga',
    'RAIDS.ALL_RAIDS': 'Tous les Raids',
    'RAIDS.ALL_LEVEL_RAIDS': 'Tous les Raids {{level}}',
    'RAIDS.RAID_SUFFIX': 'Raid',
    'RAIDS.RAID_BOSS_NUM': 'Boss de Raid #{{id}}',
    'RAIDS.POKEMON_SELECTED': '{{count}} Pokemon sélectionnés',
    'RAIDS.CLEAN_TAG': 'nettoyage',
    'RAIDS.CLEAN_TOOLTIP': 'Suppression automatique après expiration',
    'RAIDS.SNACK_CREATED_COUNT': '{{count}} alarme(s) créée(s)',
    'RAIDS.SNACK_BULK_DELETED': '{{count}} alarmes supprimées',
    'RAIDS.SNACK_BULK_DISTANCE': 'Distance mise à jour pour {{count}} alarmes',
    'RAIDS.SNACK_ALL_DISTANCE': 'Toutes les distances mises à jour',
    'RAIDS.SNACK_DELETED_ALL': 'Toutes les alarmes raid et œuf supprimées',
    'RAIDS.SNACK_FAILED_DELETE_ALL': 'Échec de la suppression des alarmes',
    'RAIDS.SNACK_FAILED_DISTANCE': 'Échec de la mise à jour des distances',
    'RAIDS.CONFIRM_DELETE_RAID_TITLE': "Supprimer l'alarme Raid",
    'RAIDS.CONFIRM_DELETE_RAID_MSG': "Es-tu sûr de vouloir supprimer l'alarme pour {{name}} ?",
    'RAIDS.CONFIRM_DELETE_EGG_TITLE': "Supprimer l'alarme Œuf",
    'RAIDS.CONFIRM_DELETE_EGG_MSG': "Es-tu sûr de vouloir supprimer l'alarme œuf {{name}} ?",
    'RAIDS.CONFIRM_DELETE_ALL_TITLE': 'Supprimer toutes les alarmes Raid et Œuf',
    'RAIDS.CONFIRM_DELETE_ALL_MSG': 'Es-tu sûr de vouloir supprimer TOUTES les alarmes raid et œuf ? Cette action est irréversible.',
    'RAIDS.CONFIRM_BULK_DELETE_TITLE': 'Supprimer les alarmes sélectionnées',
    'RAIDS.CONFIRM_BULK_DELETE_MSG': 'Es-tu sûr de vouloir supprimer {{count}} alarmes ?',
    'RAIDS.CONFIRM_DELETE_SELECTED': 'Supprimer la sélection',
    'QUESTS.TAB_SETTINGS': 'Paramètres',
    'QUESTS.CLEAN_TAG': 'nettoyage',
    'QUESTS.CLEAN_TOOLTIP': 'Suppression automatique après expiration',
    'QUESTS.SELECTION_COUNT': '{{count}} sélectionné(s)',
    'QUESTS.ANY_POKEMON_ENCOUNTER': 'Toute rencontre Pokemon',
    'QUESTS.MEGA_ENERGY_SUFFIX': 'Méga-Énergie',
    'QUESTS.CANDY_SUFFIX': 'Bonbons',
    'QUESTS.STARDUST': 'Poussière Étoile',
    'QUESTS.STARDUST_AMOUNT': '{{amount}} Poussière Étoile',
    'QUESTS.REWARD_POKEMON': 'Pokemon',
    'QUESTS.REWARD_ITEM': 'Objet',
    'QUESTS.REWARD_MEGA_ENERGY': 'Méga-Énergie',
    'QUESTS.REWARD_CANDY': 'Bonbons',
    'QUESTS.REWARD_TYPE_PREFIX': 'Type de quête :',
    'QUESTS.REWARD_POKEMON_ENCOUNTER': 'Rencontre Pokemon',
    'QUESTS.CONFIRM_DELETE_TITLE': "Supprimer l'alarme Quête",
    'QUESTS.CONFIRM_DELETE_MSG': 'Es-tu sûr de vouloir supprimer cette alarme quête ?',
    'QUESTS.CONFIRM_DELETE_ALL_TITLE': 'Supprimer toutes les alarmes Quête',
    'QUESTS.CONFIRM_DELETE_ALL_MSG': 'Es-tu sûr de vouloir supprimer TOUTES les alarmes quête ? Cette action est irréversible.',
    'QUESTS.CONFIRM_BULK_DELETE_TITLE': 'Supprimer les alarmes sélectionnées',
    'QUESTS.CONFIRM_BULK_DELETE_MSG': 'Es-tu sûr de vouloir supprimer {{count}} alarmes ?',
    'QUESTS.SNACK_CREATED_COUNT': '{{count}} alarme(s) quête créée(s)',
    'QUESTS.SNACK_BULK_DELETED': '{{count}} alarmes supprimées',
    'QUESTS.SNACK_BULK_DISTANCE': 'Distance mise à jour pour {{count}} alarmes',
    'QUESTS.SNACK_ALL_DISTANCE': 'Toutes les distances mises à jour',
    'QUESTS.SNACK_DELETED_ALL': 'Toutes les alarmes quête supprimées',
    'QUESTS.SNACK_FAILED_DELETE_ALL': 'Échec de la suppression des alarmes',
    'QUESTS.SNACK_FAILED_DISTANCE': 'Échec de la mise à jour des distances',
    'INVASIONS.CLEAN_TAG': 'nettoyage',
    'INVASIONS.CLEAN_TOOLTIP': 'Suppression automatique après expiration',
    'INVASIONS.POKESTOP_EVENT': 'Événement PokéStop',
    'INVASIONS.GENDER_ANY_LABEL': 'Tout genre',
    'INVASIONS.GENDER_LABEL': 'Genre',
    'INVASIONS.TAB_SETTINGS': 'Paramètres',
    'INVASIONS.GENDER_FILTER_NA': "Le filtre de genre ne s'applique pas aux événements PokéStop.",
    'INVASIONS.UNKNOWN_GRUNT': 'Sbire inconnu',
    'INVASIONS.SNACK_ALL_CREATED': 'Alarme toutes invasions créée',
    'INVASIONS.SNACK_CREATED_COUNT': '{{count}} alarme(s) invasion créée(s)',
    'INVASIONS.CONFIRM_DELETE_TITLE': "Supprimer l'alarme Invasion",
    'INVASIONS.CONFIRM_DELETE_MSG': 'Es-tu sûr de vouloir supprimer cette alarme invasion ?',
    'INVASIONS.CONFIRM_DELETE_ALL_TITLE': 'Supprimer toutes les alarmes Invasion',
    'INVASIONS.CONFIRM_DELETE_ALL_MSG': 'Es-tu sûr de vouloir supprimer TOUTES les alarmes invasion ? Cette action est irréversible.',
    'INVASIONS.CONFIRM_BULK_DELETE_TITLE': 'Supprimer les alarmes sélectionnées',
    'INVASIONS.CONFIRM_BULK_DELETE_MSG': 'Es-tu sûr de vouloir supprimer {{count}} alarmes ?',
    'INVASIONS.SNACK_BULK_DELETED': '{{count}} alarmes supprimées',
    'INVASIONS.SNACK_BULK_DISTANCE': 'Distance mise à jour pour {{count}} alarmes',
    'INVASIONS.SNACK_ALL_DISTANCE': 'Toutes les distances mises à jour',
    'INVASIONS.SNACK_DELETED_ALL': 'Toutes les alarmes invasion supprimées',
    'INVASIONS.SNACK_FAILED_DELETE_ALL': 'Échec de la suppression des alarmes',
    'INVASIONS.SNACK_FAILED_DISTANCE': 'Échec de la mise à jour des distances',
    'AREAS.SEARCH_AREAS': 'Rechercher des zones',
    'PROFILES.SNACK_FAILED_UPDATE': 'Échec de la mise à jour du profil',
    'PROFILES.SNACK_UPDATED': 'Profil renommé en "{{name}}"',
    'PROFILES.SNACK_FAILED_SCHEDULE': 'Échec de la mise à jour du planning',
    'PROFILES.SNACK_SCHEDULE_UPDATED': 'Planning mis à jour',
    'PROFILES.SNACK_EXPORTED': 'Sauvegarde "{{name}}" exportée',
    'PROFILES.SNACK_INVALID_BACKUP': 'Format de fichier de sauvegarde invalide',
    'PROFILES.SNACK_UNSUPPORTED_VERSION': 'Version de sauvegarde non supportée',
    'PROFILES.SNACK_FAILED_LOAD': "Échec du chargement de l'aperçu des profils",
    'PROFILES.CONFIRM_DELETE_TITLE': 'Supprimer le profil',
    'PROFILES.CONFIRM_DELETE_MSG': 'Es-tu sûr de vouloir supprimer le profil "{{name}}" (#{{number}}) ? Toutes les alarmes seront perdues.',
    'PROFILES.DUPLICATE_DIALOG_TITLE': 'Dupliquer le profil',
    'PROFILES.DUPLICATE': 'Dupliquer',
    'PROFILES.DUPLICATE_DESC': 'Créer un nouveau profil avec toutes les alarmes de {{name}}.',
    'PROFILES.NEW_PROFILE_NAME': 'Nouveau nom de profil',
    'PROFILES.IMPORT_DIALOG_TITLE': 'Importer un profil',
    'PROFILES.IMPORT_DESC': 'Créer un nouveau profil avec toutes les alarmes de cette sauvegarde.',
    'PROFILES.PROFILE_NUMBER': 'Numéro de profil',
    'PROFILES.SCHEDULE_TOOLTIP': "Modifier le planning d'heures actives",
    'PROFILES.ACTIVE_HOURS_TITLE': 'Heures actives',
    'PROFILES.ACTIVE_HOURS_DAYS': 'Jours',
    'PROFILES.ACTIVE_HOURS_WEEKDAYS': 'Jours ouvrables',
    'PROFILES.ACTIVE_HOURS_WEEKENDS': 'Week-ends',
    'PROFILES.ACTIVE_HOURS_EVERY_DAY': 'Tous les jours',
    'PROFILES.ACTIVE_HOURS_TIME': 'Heure',
    'PROFILES.ACTIVE_HOURS_HOUR': 'Heure',
    'PROFILES.ACTIVE_HOURS_MINUTE': 'Minute',
    'PROFILES.ACTIVE_HOURS_ADD': 'Ajouter',
    'PROFILES.ACTIVE_HOURS_ADD_TOOLTIP': "Ajouter une règle d'activation",
    'PROFILES.ACTIVE_HOURS_RULES': 'Règles',
    'PROFILES.ACTIVE_HOURS_NO_RULES': "Aucune règle d'activation. Le profil nécessitera un démarrage manuel.",
    'PROFILES.ACTIVE_HOURS_REMOVE_RULE': 'Supprimer la règle',
    'PROFILES.ACTIVE_HOURS_WEEKLY_PREVIEW': 'Aperçu hebdomadaire',
    'PROFILES.ACTIVE_HOURS_CLEAR_ALL': 'Tout effacer',
    'GEOFENCES.CONFIRM_DELETE_TITLE': 'Supprimer la geofence personnalisée',
    'GEOFENCES.CONFIRM_DELETE_MSG': 'Es-tu sûr de vouloir supprimer "{{name}}" ?',
    'GEOFENCES.SNACK_FAILED_UPDATE': 'Échec de la mise à jour de la geofence',
    'GEOFENCES.SNACK_UPDATED': 'Geofence mise à jour',
    'GEOFENCES.SNACK_NO_EXPORT': 'Aucune geofence à exporter',
    'GEOFENCES.SNACK_MIN_POINTS': 'Une geofence nécessite au moins 3 points',
    'GEOFENCES.SNACK_IMPORTED': '{{count}} geofence(s) importée(s)',
    'GEOFENCES.SUBMIT_CONFIRM_TITLE': 'Soumettre la geofence pour révision publique',
    'GEOFENCES.SUBMIT_CONFIRM_TEXT': 'Soumettre pour révision',
    'GEOFENCES.SUBMIT_CONFIRM_MSG': '"{{name}}" sera envoyée à l\'équipe admin pour révision.',
    'GEOFENCES.SNACK_FAILED_ACTIVATE': "Échec de l'activation de la geofence",
    'GEOFENCES.SNACK_FAILED_DEACTIVATE': 'Échec de la désactivation de la geofence',
    'GEOFENCES.SNACK_EXPORTED': '{{count}} geofence(s) exportée(s)',
    'GEOFENCES.NAME_DIALOG_TITLE': 'Nomme ta geofence',
    'GEOFENCES.NAME_LABEL': 'Nom de la geofence',
    'GEOFENCES.NAME_PLACEHOLDER': 'ex. Mon parcours du parc',
    'GEOFENCES.NAME_WHITESPACE_ERROR': 'Le nom ne peut pas être uniquement des espaces',
    'GEOFENCES.NAME_INVALID_CHARS_ERROR': 'Seuls les lettres, chiffres, espaces, tirets, apostrophes et parenthèses sont autorisés',
    'GEOFENCES.REGION_LABEL': 'Région',
    'GEOFENCES.CHANGE_REGION': 'Modifier',
    'GEOFENCES.SELECT_REGION': 'Sélectionner une région',
    'GEOFENCES.SEARCH_REGIONS': 'Rechercher des régions...',
    'CLEANING.LABEL_EGGS': 'Œufs',
    'QUICK_PICKS.SNACK_FAILED_LOAD': 'Échec du chargement des sélections rapides',
    'QUICK_PICKS.CONFIRM_DELETE_TITLE': 'Supprimer la sélection rapide',
    'QUICK_PICKS.CONFIRM_DELETE_MSG': 'Supprimer définitivement "{{name}}" ?',
    'QUICK_PICKS.SNACK_FAILED_DELETE': 'Échec de la suppression',
    'QUICK_PICKS.SNACK_DELETED': 'Sélection rapide supprimée',
    'QUICK_PICKS.CONFIRM_REMOVE_TITLE': 'Retirer la sélection rapide',
    'QUICK_PICKS.CONFIRM_REMOVE_MSG': 'Retirer "{{name}}" ? Cela supprimera {{count}} alarme(s).',
    'QUICK_PICKS.SNACK_FAILED_REMOVE': 'Échec du retrait',
    'QUICK_PICKS.SNACK_REMOVED': 'Sélection rapide retirée -- {{count}} alarme(s) supprimée(s)',
    'QUICK_PICKS.CONFIRM_RESET_MSG': 'Cela supprimera toutes les sélections rapides admin et recréera les valeurs par défaut.',
    'QUICK_PICKS.SNACK_FAILED_RESET': 'Échec de la restauration des valeurs par défaut',
    'QUICK_PICKS.SNACK_RESET': 'Valeurs par défaut restaurées',
    'QUICK_PICKS.SNACK_FAILED_SAVE': 'Échec de la sauvegarde de la sélection rapide',
    'QUICK_PICKS.SNACK_UPDATED': 'Sélection rapide mise à jour',
    'QUICK_PICKS.SNACK_CREATED_QP': 'Sélection rapide créée',
    'QUICK_PICKS.APPLY_STATUS_CREATING': 'Création de {{count}} alarmes individuelles...',
    'QUICK_PICKS.APPLY_STATUS_APPLYING': 'Application de la sélection rapide...',
    'QUICK_PICKS.SNACK_FAILED_APPLY': "Échec de l'application de la sélection rapide",
    'QUICK_PICKS.SNACK_APPLIED': 'Sélection rapide appliquée : {{count}} alarme(s) créée(s)',
    'QUICK_PICKS.TAB_OPTIONS': 'Options',
    'QUICK_PICKS.EXCLUDE_POKEMON': 'Exclure certains Pokemon',
    'QUICK_PICKS.EXCLUDE_HINT': 'Ignorer certains Pokemon de cette sélection rapide.',
    'QUICK_PICKS.EXCLUDED_SUMMARY': '{{count}} Pokemon exclus',
    'QUICK_PICKS.INDIVIDUAL_WARNING': 'Cela créera {{count}} lignes d\'alarme individuelles.',
    'QUICK_PICKS.NO_OPTIONS_HINT': "Aucune option supplémentaire. Passe à l'onglet Livraison.",
    'QUICK_PICKS.TAB_DELIVERY': 'Livraison',
    'QUICK_PICKS.CLEAN_HINT': 'Supprime automatiquement la notification après expiration',
    'QUICK_PICKS.APPLYING': 'Application...',
    'QUICK_PICKS.APPLY_WITH_COUNT': 'Appliquer ({{count}} alarmes)',
    'QUICK_PICKS.EDIT_DIALOG_TITLE': 'Modifier la sélection rapide',
    'QUICK_PICKS.CREATE_DIALOG_TITLE': 'Créer une sélection rapide',
    'QUICK_PICKS.FIELD_NAME': 'Nom',
    'QUICK_PICKS.FIELD_DESCRIPTION': 'Description',
    'QUICK_PICKS.FIELD_ICON': 'Icône',
    'QUICK_PICKS.FIELD_CATEGORY': 'Catégorie',
    'QUICK_PICKS.FIELD_ALARM_TYPE': "Type d'alarme",
    'QUICK_PICKS.FIELD_SORT_ORDER': 'Ordre de tri',
    'QUICK_PICKS.FILTER_SETTINGS': 'Paramètres de filtre',
    'QUICK_PICKS.FIELD_POKEMON_ID': 'ID Pokemon',
    'QUICK_PICKS.FIELD_EXCLUSIVE': 'Exclusif',
    'QUICK_PICKS.FIELD_REWARD_TYPE': 'Type de récompense',
    'QUICK_PICKS.FIELD_REWARD': 'Récompense',
    'QUICK_PICKS.FIELD_SHINY': 'Shiny',
    'QUICK_PICKS.FIELD_GRUNT_TYPE': 'Type de sbire',
    'QUICK_PICKS.FIELD_LURE_ID': 'ID de leurre',
    'QUICK_PICKS.FIELD_MOVE': 'Attaque',
    'QUICK_PICKS.FIELD_EVOLUTION': 'Évolution',
    'AUTH.SITE_TITLE_DEFAULT': 'Alertes DM',
    'AUTH.AUTH_FAILED': 'Échec de l\'authentification',
    'AUTH.BACK_TO_LOGIN': 'Retour à la connexion',
    'AUTH.ERR_DISCORD_FETCH': "Échec de la récupération des informations utilisateur Discord.",
    'AUTH.ERR_MISSING_CODE': "Aucun code d'autorisation reçu de Discord.",
    'AUTH.ERR_TOKEN_EXCHANGE': "Échec de l'échange du code d'autorisation avec Discord.",
    'AUTH.ERR_NOT_REGISTERED': "Ton compte n'est pas enregistré dans Poracle.",
    'AUTH.ERR_GENERIC': "Erreur d'authentification : {{error}}",
    'AUTH.ERR_NO_TOKEN': "Aucun jeton d'authentification reçu.",
    'ADMIN.APPROVAL_DIALOG_TITLE': 'Examiner la geofence',
    'ADMIN.APPROVAL_NAME': 'Nom',
    'ADMIN.APPROVAL_GROUP': 'Groupe',
    'ADMIN.APPROVAL_SUBMITTED': 'Soumis',
    'ADMIN.APPROVAL_APPROVE': 'Approuver',
    'ADMIN.APPROVAL_REJECT': 'Rejeter',
    'ADMIN.APPROVAL_PROMOTED_NAME': 'Nom promu',
    'ADMIN.APPROVAL_PROMOTED_NAME_PLACEHOLDER': 'Nom pour la geofence promue',
    'ADMIN.APPROVAL_PROMOTED_NAME_HINT': "Optionnel. Par défaut, le nom d'affichage actuel.",
    'ADMIN.APPROVAL_REJECT_REASON': 'Raison du rejet',
    'ADMIN.APPROVAL_REJECT_PLACEHOLDER': 'Explique pourquoi cette geofence est rejetée...',
    'ADMIN.USERS_DESC_FULL': 'Gérer les utilisateurs Discord inscrits. <strong>Arrêté</strong> = alertes en pause ou limite atteinte. <strong>Bloqué</strong> = bloqué par un admin.',
    'ADMIN.COLUMN_DISABLED_SINCE': 'Désactivé depuis',
    'ADMIN.COLUMN_URL': 'URL',
    'ADMIN.COLUMN_DELEGATES': 'Délégués',
    'ADMIN.COLUMN_OWNER': 'Propriétaire',
    'ADMIN.COLUMN_REGION': 'Région',
    'ADMIN.COLUMN_POINTS': 'Points',
    'ADMIN.COLUMN_CREATED': 'Créé',
    'ADMIN.COLUMN_SUBMITTED': 'Soumis',
    'ADMIN.COLUMN_REVIEWED_BY': 'Examiné par',
    'ADMIN.TRY_ADJUSTING_FILTERS': 'Essaie d\'ajuster tes filtres.',
    'ADMIN.NO_USERS_YET': 'Aucun utilisateur inscrit pour le moment.',
    'ADMIN.CONFIRM_DELETE_ALARMS': 'Es-tu sûr de vouloir supprimer TOUTES les alarmes pour "{{name}}" ? Cette action est irréversible.',
    'ADMIN.CONFIRM_DELETE_USER': 'Es-tu sûr de vouloir supprimer définitivement "{{name}}" ?',
    'ADMIN.SNACK_FAILED_IMPERSONATE': "Échec de l'usurpation d'identité",
    'ADMIN.SNACK_FAILED_LOAD_USERS': 'Échec du chargement des utilisateurs',
    'ADMIN.WEBHOOKS_TITLE': 'Webhooks',
    'ADMIN.WEBHOOKS_DESC': 'Gérer les destinations webhook enregistrées.',
    'ADMIN.ADD_WEBHOOK': 'Ajouter un Webhook',
    'ADMIN.SEARCH_WEBHOOKS': 'Rechercher des webhooks',
    'ADMIN.FILTER_WEBHOOK_PLACEHOLDER': 'Filtrer par nom ou URL...',
    'ADMIN.CLICK_TO_COPY': 'Cliquer pour copier',
    'ADMIN.GLOBAL_ADMIN': 'admin global',
    'ADMIN.CONFIG_DELEGATE': 'délégué config',
    'ADMIN.BLOCK_WEBHOOK': 'Bloquer le webhook',
    'ADMIN.UNBLOCK_WEBHOOK': 'Débloquer le webhook',
    'ADMIN.MANAGE_ALARMS': 'Gérer les alarmes',
    'ADMIN.MANAGE_ALARMS_TOOLTIP': 'Gérer les alarmes pour ce webhook',
    'ADMIN.MANAGE_DELEGATES': 'Gérer les délégués',
    'ADMIN.DELETE_WEBHOOK': 'Supprimer le webhook',
    'ADMIN.NO_WEBHOOKS': 'Aucun webhook trouvé',
    'ADMIN.NO_WEBHOOKS_YET': 'Aucun webhook enregistré.',
    'ADMIN.CONFIRM_DELETE_WEBHOOK': 'Es-tu sûr de vouloir supprimer définitivement "{{name}}" ?',
    'ADMIN.SNACK_FAILED_DELETE_WEBHOOK': 'Échec de la suppression du webhook',
    'ADMIN.SNACK_WEBHOOK_DELETED': '"{{name}}" supprimé',
    'ADMIN.SNACK_URL_COPIED': 'URL copiée dans le presse-papiers',
    'ADMIN.SNACK_FAILED_LOAD_WEBHOOKS': 'Échec du chargement des webhooks',
    'ADMIN.SNACK_FAILED_SWITCH_WEBHOOK': 'Échec du basculement vers le contexte webhook',
    'ADMIN.SNACK_FAILED_ADD_WEBHOOK': "Échec de l'ajout du webhook",
    'ADMIN.SNACK_WEBHOOK_ADDED': 'Webhook "{{name}}" ajouté',
    'ADMIN.SNACK_FAILED_ADD_DELEGATE': "Échec de l'ajout du délégué",
    'ADMIN.SNACK_FAILED_LOAD_DELEGATES': 'Échec du chargement des délégués',
    'ADMIN.SNACK_FAILED_REMOVE_DELEGATE': 'Échec de la suppression du délégué',
    'ADMIN.MANAGE_DELEGATES_TITLE': 'Gérer les délégués',
    'ADMIN.DELEGATES_HINT': 'Les délégués peuvent gérer les alarmes pour ce webhook.',
    'ADMIN.GLOBAL_ADMIN_TOOLTIP': 'Admin global (depuis la config Poracle)',
    'ADMIN.CONFIG_DELEGATE_TOOLTIP': 'Délégué depuis la config Poracle (lecture seule)',
    'ADMIN.REMOVE_DELEGATE': 'Retirer le délégué',
    'ADMIN.SEARCH_USER_LABEL': 'Rechercher un utilisateur par nom ou ID',
    'ADMIN.SEARCH_USER_PLACEHOLDER': 'Nom ou ID utilisateur Discord...',
    'ADMIN.WEBHOOK_NAME': 'Nom',
    'ADMIN.WEBHOOK_NAME_PLACEHOLDER': 'ex. #pogo-alerts',
    'ADMIN.WEBHOOK_NAME_REQUIRED': 'Le nom est requis',
    'ADMIN.WEBHOOK_URL': 'URL du Webhook',
    'ADMIN.WEBHOOK_URL_PLACEHOLDER': 'https://discord.com/api/webhooks/...',
    'ADMIN.WEBHOOK_URL_REQUIRED': "L'URL est requise",
    'ADMIN.WEBHOOK_URL_INVALID': 'Doit être une URL https:// valide',
    'ADMIN.MY_WEBHOOKS_TITLE': 'Mes Webhooks',
    'ADMIN.MY_WEBHOOKS_DESC': 'Webhooks dont tu es délégué.',
    'ADMIN.NO_WEBHOOKS_ASSIGNED': 'Aucun webhook assigné',
    'ADMIN.NO_WEBHOOKS_ASSIGNED_DESC': "Tu n'as été assigné comme délégué pour aucun webhook.",
    'ADMIN.GEOFENCES_TITLE': 'Geofences utilisateurs',
    'ADMIN.GEOFENCES_DESC': 'Examiner les soumissions, gérer les geofences utilisateurs et nettoyer les enregistrements.',
    'ADMIN.GEO_STATUS_PENDING': 'En attente',
    'ADMIN.GEO_STATUS_APPROVED': 'Approuvée',
    'ADMIN.GEO_STATUS_REJECTED': 'Rejetée',
    'ADMIN.VIEW_CARD': 'Vue carte (groupée par région)',
    'ADMIN.VIEW_LIST': 'Vue liste (groupée par région)',
    'ADMIN.VIEW_TABLE': 'Vue tableau (toutes les geofences)',
    'ADMIN.VIEW_DETAILS': 'Voir les détails',
    'ADMIN.VIEW_GEOFENCE_DETAILS': 'Voir les détails de la geofence',
    'ADMIN.REVIEW': 'Examiner',
    'ADMIN.REVIEW_SUBMISSION': 'Examiner cette soumission',
    'ADMIN.DELETE_GEOFENCE': 'Supprimer la geofence et nettoyer',
    'ADMIN.NO_POLYGON_DATA': 'Aucune donnée de polygone',
    'ADMIN.POINTS': 'points',
    'ADMIN.CREATED': 'Créé',
    'ADMIN.SUBMITTED': 'Soumis',
    'ADMIN.REVIEWED_BY': 'Examiné par',
    'ADMIN.PROMOTED_AS': 'Promue en tant que :',
    'ADMIN.NO_REGION': 'Aucune région',
    'ADMIN.NO_GEOFENCES': 'Aucune geofence',
    'ADMIN.NO_PENDING_SUBMISSIONS': "Aucune soumission n'attend d'être examinée.",
    'ADMIN.NO_GEOFENCES_YET': "Aucune geofence créée par les utilisateurs pour le moment.",
    'ADMIN.NO_GEOFENCES_STATUS': 'Aucune geofence avec ce statut.',
    'ADMIN.CONFIRM_DELETE_GEOFENCE': 'Supprimer définitivement "{{name}}" (propriétaire : {{owner}}) ?',
    'ADMIN.ADMIN_DELETE_GEOFENCE': 'Suppression admin de geofence',
    'ADMIN.SNACK_FAILED_DELETE_GEOFENCE': 'Échec de la suppression de la geofence',
    'ADMIN.SNACK_GEOFENCE_DELETED': '"{{name}}" supprimée',
    'ADMIN.SNACK_FAILED_LOAD_GEOFENCES': 'Échec du chargement des geofences',
    'ADMIN.SNACK_FAILED_APPROVE': "Échec de l'approbation de la soumission",
    'ADMIN.SNACK_APPROVED': '"{{name}}" approuvée',
    'ADMIN.SNACK_FAILED_REJECT': 'Échec du rejet de la soumission',
    'ADMIN.SNACK_REJECTED': '"{{name}}" rejetée',
    'ADMIN.SERVERS_TITLE': 'Serveurs Poracle',
    'ADMIN.SERVERS_DESC': 'Surveiller le statut des serveurs et redémarrer les instances Poracle.',
    'ADMIN.REFRESH_STATUS': 'Actualiser le statut du serveur',
    'ADMIN.RESTART_ALL': 'Tout redémarrer',
    'ADMIN.RESTART_ALL_TOOLTIP': 'Redémarrer tous les serveurs Poracle',
    'ADMIN.RESTART_ALL_TITLE': 'Redémarrer tous les serveurs Poracle',
    'ADMIN.CONFIRM_RESTART_ALL': 'Cela redémarrera TOUS les serveurs Poracle. Les utilisateurs cesseront brièvement de recevoir des alertes.',
    'ADMIN.RESTART': 'Redémarrer',
    'ADMIN.RESTART_SERVER': 'Redémarrer ce serveur',
    'ADMIN.RESTART_SERVER_TITLE': 'Redémarrer le serveur Poracle',
    'ADMIN.CONFIRM_RESTART_SERVER': 'Es-tu sûr de vouloir redémarrer "{{name}}" ({{host}}) ?',
    'ADMIN.SERVER_ONLINE': 'En ligne',
    'ADMIN.SERVER_OFFLINE': 'Hors ligne',
    'ADMIN.CHECKED': 'Vérifié',
    'ADMIN.NO_SERVERS': 'Aucun serveur Poracle trouvé',
    'ADMIN.NO_SERVERS_DESC': "Aucune instance de serveur Poracle n'est configurée.",
    'ADMIN.SNACK_FAILED_RESTART_ALL': 'Échec du redémarrage des serveurs',
    'ADMIN.SNACK_ALL_RESTARTED': 'Tous les serveurs redémarrés',
    'ADMIN.SNACK_FAILED_RESTART': 'Échec du redémarrage de "{{name}}"',
    'ADMIN.SNACK_RESTARTED': '"{{name}}" redémarré',
    'ADMIN.SNACK_FAILED_LOAD_SERVERS': 'Échec du chargement des serveurs Poracle',
    'DIALOG.LOCATION_SAVE_ERROR': 'Échec de la mise à jour de la localisation',
    'DIALOG.LOCATION_SAVE_SUCCESS': 'Localisation mise à jour avec succès',
    'DIALOG.LOCATION_GEO_UNSUPPORTED': "La géolocalisation n'est pas supportée par ton navigateur",
    'DIALOG.LOCATION_GEO_UNABLE': 'Impossible de récupérer la localisation',
    'DIALOG.LOCATION_GEO_DENIED': 'Permission de localisation refusée',
    'POKEMON_SELECTOR.GEN': 'Gén',
    'POKEMON_SELECTOR.TYPE': 'Type',
    'POKEMON_SELECTOR.LIVE': 'En direct',
    'POKEMON_SELECTOR.SPAWNING': 'Spawn actif',
    'POKEMON_SELECTOR.SPECIES_ACTIVE': '{{count}} espèces actives',
    'POKEMON_SELECTOR.SEARCH_LABEL': 'Rechercher un Pokemon',
    'POKEMON_SELECTOR.SEARCH_HINT': 'Tape un nom ou ID...',
    'POKEMON_SELECTOR.CURRENTLY_SPAWNING': 'En cours de spawn',
    'TEMPLATE_SELECTOR.LABEL': 'Modèle',
    'TEMPLATE_SELECTOR.DEFAULT': 'Par défaut',
    'TEMPLATE_SELECTOR.TEMPLATE_NUM': 'Modèle {{num}}',
    'TEMPLATE_SELECTOR.HINT': 'Format du message de notification',
    'TEMPLATE_SELECTOR.HIDE_OPTIONS': 'Masquer les options',
    'TEMPLATE_SELECTOR.PREVIEW_OPTIONS': 'Options de prévisualisation',
    'TEMPLATE_SELECTOR.MAP_PREVIEW': 'Aperçu de la carte',
    'REGION_SELECTOR.ALL_REGIONS': 'Toutes les régions',
    'GYM_PICKER.SEARCH_LABEL': 'Rechercher une arène (optionnel)',
    'GYM_PICKER.SEARCH_HINT': "Tape le nom de l'arène...",
    'GYM_PICKER.CLEAR_ARIA': "Effacer la sélection d'arène",
    'DELIVERY_PREVIEW.AREAS_LABEL': 'Les notifications seront envoyées pour ces zones :',
    'DELIVERY_PREVIEW.NO_AREAS': 'Aucune zone configurée.',
    'DELIVERY_PREVIEW.SET_UP_AREAS': 'Configurer les zones',
    'DELIVERY_PREVIEW.FIRST': "d'abord.",
    'DELIVERY_PREVIEW.DISTANCE_LABEL': 'Notifications dans un rayon de {{distance}} km autour de ta position :',
    'DELIVERY_PREVIEW.MAP_ALT': 'Carte du rayon de distance',
    'LOCATION_WARNING.TEXT': 'Aucune localisation définie \u2014 le planning pourrait utiliser le mauvais fuseau horaire',
    'LOCATION_WARNING.TOOLTIP': "Les heures actives utilisent la localisation du profil pour déterminer le fuseau horaire. Sans localisation définie, le planning pourrait s'activer au mauvais moment.",
    'ACTIVE_HOURS_CHIP.MANUAL_ONLY': 'Manuel uniquement',
    'ACTIVE_HOURS_CHIP.NO_SCHEDULE': 'Aucun planning défini \u2014 le profil fonctionne manuellement ou en continu',
    'ALARM_INFO.PING_TOOLTIP': 'Ping : {{ping}}'
  },
  es: {
    'DASHBOARD.WEATHER_1_MIN_AGO': 'Hace 1 min',
    'DASHBOARD.WEATHER_1_HR_AGO': 'Hace 1 h',
    'DASHBOARD.WEATHER_HRS_AGO': 'Hace {{count}} h',
    'DASHBOARD.SWITCH_PROFILE_SUCCESS': 'Cambiado a "{{name}}"',
    'DASHBOARD.SWITCH_PROFILE_FAILED': 'Error al cambiar de perfil',
    'ONBOARDING.ARIA_LABEL': 'Bienvenida onboarding',
    'POKEMON.ADD_POKEMON': 'Añadir Pokemon',
    'POKEMON.LABEL_FORM_ID': 'ID de forma',
    'POKEMON.FILTER_IV_CP_LEVEL': 'IV / CP / Nivel',
    'POKEMON.FILTER_STATS_SECTION': 'Estadísticas',
    'POKEMON.PVP_NONE_EDIT': 'Ninguna',
    'POKEMON.PVP_LITTLE_CUP_SHORT': 'Copa Junior (500)',
    'POKEMON.PVP_GREAT_LEAGUE_SHORT': 'Liga Super (1500)',
    'POKEMON.PVP_ULTRA_LEAGUE_SHORT': 'Liga Hiper (2500)',
    'POKEMON.PVP_LEAGUE_SUFFIX': 'Liga',
    'POKEMON.PVP_RANK_RANGE': 'Rango {{best}}-{{worst}}',
    'POKEMON.PVP_BEST_RANK_HINT': 'ej. 1',
    'POKEMON.PVP_WORST_RANK_HINT': 'ej. 100',
    'ALARM.TAB_DELIVERY': 'Entrega',
    'ALARM.COMMON_SETTINGS': 'Ajustes comunes',
    'RAIDS.LEVEL_MEGA': 'Mega',
    'RAIDS.ALL_RAIDS': 'Todos los Raids',
    'RAIDS.ALL_LEVEL_RAIDS': 'Todos los Raids {{level}}',
    'RAIDS.RAID_SUFFIX': 'Raid',
    'RAIDS.RAID_BOSS_NUM': 'Jefe de Raid #{{id}}',
    'RAIDS.POKEMON_SELECTED': '{{count}} Pokemon seleccionados',
    'RAIDS.CLEAN_TAG': 'limpieza',
    'RAIDS.CLEAN_TOOLTIP': 'Se elimina automáticamente tras expirar',
    'RAIDS.SNACK_CREATED_COUNT': '{{count}} alarma(s) creada(s)',
    'RAIDS.SNACK_BULK_DELETED': '{{count}} alarmas eliminadas',
    'RAIDS.SNACK_BULK_DISTANCE': 'Distancia actualizada para {{count}} alarmas',
    'RAIDS.SNACK_ALL_DISTANCE': 'Todas las distancias actualizadas',
    'RAIDS.SNACK_DELETED_ALL': 'Todas las alarmas de raid y huevo eliminadas',
    'RAIDS.SNACK_FAILED_DELETE_ALL': 'Error al eliminar las alarmas',
    'RAIDS.SNACK_FAILED_DISTANCE': 'Error al actualizar las distancias',
    'RAIDS.CONFIRM_DELETE_RAID_TITLE': 'Eliminar alarma de Raid',
    'RAIDS.CONFIRM_DELETE_RAID_MSG': '¿Seguro que quieres eliminar la alarma de {{name}}?',
    'RAIDS.CONFIRM_DELETE_EGG_TITLE': 'Eliminar alarma de Huevo',
    'RAIDS.CONFIRM_DELETE_EGG_MSG': '¿Seguro que quieres eliminar la alarma de huevo {{name}}?',
    'RAIDS.CONFIRM_DELETE_ALL_TITLE': 'Eliminar todas las alarmas de Raid y Huevo',
    'RAIDS.CONFIRM_DELETE_ALL_MSG': '¿Seguro que quieres eliminar TODAS las alarmas de raid y huevo? Esta acción no se puede deshacer.',
    'RAIDS.CONFIRM_BULK_DELETE_TITLE': 'Eliminar alarmas seleccionadas',
    'RAIDS.CONFIRM_BULK_DELETE_MSG': '¿Seguro que quieres eliminar {{count}} alarmas?',
    'RAIDS.CONFIRM_DELETE_SELECTED': 'Eliminar seleccionadas',
    'QUESTS.TAB_SETTINGS': 'Ajustes',
    'QUESTS.CLEAN_TAG': 'limpieza',
    'QUESTS.CLEAN_TOOLTIP': 'Se elimina automáticamente tras expirar',
    'QUESTS.SELECTION_COUNT': '{{count}} seleccionados',
    'QUESTS.ANY_POKEMON_ENCOUNTER': 'Cualquier encuentro Pokemon',
    'QUESTS.MEGA_ENERGY_SUFFIX': 'Megaenergía',
    'QUESTS.CANDY_SUFFIX': 'Caramelos',
    'QUESTS.STARDUST': 'Polvo Estelar',
    'QUESTS.STARDUST_AMOUNT': '{{amount}} Polvo Estelar',
    'QUESTS.REWARD_POKEMON': 'Pokemon',
    'QUESTS.REWARD_ITEM': 'Objeto',
    'QUESTS.REWARD_MEGA_ENERGY': 'Megaenergía',
    'QUESTS.REWARD_CANDY': 'Caramelos',
    'QUESTS.REWARD_TYPE_PREFIX': 'Tipo de misión:',
    'QUESTS.REWARD_POKEMON_ENCOUNTER': 'Encuentro Pokemon',
    'QUESTS.CONFIRM_DELETE_TITLE': 'Eliminar alarma de Misión',
    'QUESTS.CONFIRM_DELETE_MSG': '¿Seguro que quieres eliminar esta alarma de misión?',
    'QUESTS.CONFIRM_DELETE_ALL_TITLE': 'Eliminar todas las alarmas de Misión',
    'QUESTS.CONFIRM_DELETE_ALL_MSG': '¿Seguro que quieres eliminar TODAS las alarmas de misión? Esta acción no se puede deshacer.',
    'QUESTS.CONFIRM_BULK_DELETE_TITLE': 'Eliminar alarmas seleccionadas',
    'QUESTS.CONFIRM_BULK_DELETE_MSG': '¿Seguro que quieres eliminar {{count}} alarmas?',
    'QUESTS.SNACK_CREATED_COUNT': '{{count}} alarma(s) de misión creada(s)',
    'QUESTS.SNACK_BULK_DELETED': '{{count}} alarmas eliminadas',
    'QUESTS.SNACK_BULK_DISTANCE': 'Distancia actualizada para {{count}} alarmas',
    'QUESTS.SNACK_ALL_DISTANCE': 'Todas las distancias actualizadas',
    'QUESTS.SNACK_DELETED_ALL': 'Todas las alarmas de misión eliminadas',
    'QUESTS.SNACK_FAILED_DELETE_ALL': 'Error al eliminar las alarmas',
    'QUESTS.SNACK_FAILED_DISTANCE': 'Error al actualizar las distancias',
    'INVASIONS.CLEAN_TAG': 'limpieza',
    'INVASIONS.CLEAN_TOOLTIP': 'Se elimina automáticamente tras expirar',
    'INVASIONS.POKESTOP_EVENT': 'Evento de PokéStop',
    'INVASIONS.GENDER_ANY_LABEL': 'Cualquier género',
    'INVASIONS.GENDER_LABEL': 'Género',
    'INVASIONS.TAB_SETTINGS': 'Ajustes',
    'INVASIONS.GENDER_FILTER_NA': 'El filtro de género no aplica a eventos de PokéStop.',
    'INVASIONS.UNKNOWN_GRUNT': 'Recluta desconocido',
    'INVASIONS.SNACK_ALL_CREATED': 'Alarma de todas las invasiones creada',
    'INVASIONS.SNACK_CREATED_COUNT': '{{count}} alarma(s) de invasión creada(s)',
    'INVASIONS.CONFIRM_DELETE_TITLE': 'Eliminar alarma de Invasión',
    'INVASIONS.CONFIRM_DELETE_MSG': '¿Seguro que quieres eliminar esta alarma de invasión?',
    'INVASIONS.CONFIRM_DELETE_ALL_TITLE': 'Eliminar todas las alarmas de Invasión',
    'INVASIONS.CONFIRM_DELETE_ALL_MSG': '¿Seguro que quieres eliminar TODAS las alarmas de invasión? Esta acción no se puede deshacer.',
    'INVASIONS.CONFIRM_BULK_DELETE_TITLE': 'Eliminar alarmas seleccionadas',
    'INVASIONS.CONFIRM_BULK_DELETE_MSG': '¿Seguro que quieres eliminar {{count}} alarmas?',
    'INVASIONS.SNACK_BULK_DELETED': '{{count}} alarmas eliminadas',
    'INVASIONS.SNACK_BULK_DISTANCE': 'Distancia actualizada para {{count}} alarmas',
    'INVASIONS.SNACK_ALL_DISTANCE': 'Todas las distancias actualizadas',
    'INVASIONS.SNACK_DELETED_ALL': 'Todas las alarmas de invasión eliminadas',
    'INVASIONS.SNACK_FAILED_DELETE_ALL': 'Error al eliminar las alarmas',
    'INVASIONS.SNACK_FAILED_DISTANCE': 'Error al actualizar las distancias',
    'AREAS.SEARCH_AREAS': 'Buscar zonas',
    'PROFILES.SNACK_FAILED_UPDATE': 'Error al actualizar el perfil',
    'PROFILES.SNACK_UPDATED': 'Perfil renombrado a "{{name}}"',
    'PROFILES.SNACK_FAILED_SCHEDULE': 'Error al actualizar el horario',
    'PROFILES.SNACK_SCHEDULE_UPDATED': 'Horario actualizado',
    'PROFILES.SNACK_EXPORTED': 'Respaldo de "{{name}}" exportado',
    'PROFILES.SNACK_INVALID_BACKUP': 'Formato de archivo de respaldo inválido',
    'PROFILES.SNACK_UNSUPPORTED_VERSION': 'Versión de respaldo no soportada',
    'PROFILES.SNACK_FAILED_LOAD': 'Error al cargar la vista de perfiles',
    'PROFILES.CONFIRM_DELETE_TITLE': 'Eliminar perfil',
    'PROFILES.CONFIRM_DELETE_MSG': '¿Seguro que quieres eliminar el perfil "{{name}}" (#{{number}})? Se perderán todas las alarmas.',
    'PROFILES.DUPLICATE_DIALOG_TITLE': 'Duplicar perfil',
    'PROFILES.DUPLICATE': 'Duplicar',
    'PROFILES.DUPLICATE_DESC': 'Crear un nuevo perfil con todas las alarmas de {{name}}.',
    'PROFILES.NEW_PROFILE_NAME': 'Nuevo nombre de perfil',
    'PROFILES.IMPORT_DIALOG_TITLE': 'Importar perfil',
    'PROFILES.IMPORT_DESC': 'Crear un nuevo perfil con todas las alarmas de este respaldo.',
    'PROFILES.PROFILE_NUMBER': 'Número de perfil',
    'PROFILES.SCHEDULE_TOOLTIP': 'Editar horario de horas activas',
    'PROFILES.ACTIVE_HOURS_TITLE': 'Horas activas',
    'PROFILES.ACTIVE_HOURS_DAYS': 'Días',
    'PROFILES.ACTIVE_HOURS_WEEKDAYS': 'Días laborables',
    'PROFILES.ACTIVE_HOURS_WEEKENDS': 'Fines de semana',
    'PROFILES.ACTIVE_HOURS_EVERY_DAY': 'Todos los días',
    'PROFILES.ACTIVE_HOURS_TIME': 'Hora',
    'PROFILES.ACTIVE_HOURS_HOUR': 'Hora',
    'PROFILES.ACTIVE_HOURS_MINUTE': 'Minuto',
    'PROFILES.ACTIVE_HOURS_ADD': 'Añadir',
    'PROFILES.ACTIVE_HOURS_ADD_TOOLTIP': 'Añadir regla de activación',
    'PROFILES.ACTIVE_HOURS_RULES': 'Reglas',
    'PROFILES.ACTIVE_HOURS_NO_RULES': 'Sin reglas de activación. El perfil requiere inicio manual.',
    'PROFILES.ACTIVE_HOURS_REMOVE_RULE': 'Eliminar regla',
    'PROFILES.ACTIVE_HOURS_WEEKLY_PREVIEW': 'Vista previa semanal',
    'PROFILES.ACTIVE_HOURS_CLEAR_ALL': 'Borrar todo',
    'GEOFENCES.CONFIRM_DELETE_TITLE': 'Eliminar geofence personalizada',
    'GEOFENCES.CONFIRM_DELETE_MSG': '¿Seguro que quieres eliminar "{{name}}"?',
    'GEOFENCES.SNACK_FAILED_UPDATE': 'Error al actualizar la geofence',
    'GEOFENCES.SNACK_UPDATED': 'Geofence actualizada',
    'GEOFENCES.SNACK_NO_EXPORT': 'No hay geofences para exportar',
    'GEOFENCES.SNACK_MIN_POINTS': 'Una geofence necesita al menos 3 puntos',
    'GEOFENCES.SNACK_IMPORTED': '{{count}} geofence(s) importada(s)',
    'GEOFENCES.SUBMIT_CONFIRM_TITLE': 'Enviar geofence para revisión pública',
    'GEOFENCES.SUBMIT_CONFIRM_TEXT': 'Enviar para revisión',
    'GEOFENCES.SUBMIT_CONFIRM_MSG': '"{{name}}" será enviada al equipo admin para revisión.',
    'GEOFENCES.SNACK_FAILED_ACTIVATE': 'Error al activar la geofence',
    'GEOFENCES.SNACK_FAILED_DEACTIVATE': 'Error al desactivar la geofence',
    'GEOFENCES.SNACK_EXPORTED': '{{count}} geofence(s) exportada(s)',
    'GEOFENCES.NAME_DIALOG_TITLE': 'Nombra tu geofence',
    'GEOFENCES.NAME_LABEL': 'Nombre de la geofence',
    'GEOFENCES.NAME_PLACEHOLDER': 'ej. Mi ruta del parque',
    'GEOFENCES.NAME_WHITESPACE_ERROR': 'El nombre no puede ser solo espacios',
    'GEOFENCES.NAME_INVALID_CHARS_ERROR': 'Solo se permiten letras, números, espacios, guiones, apóstrofos y paréntesis',
    'GEOFENCES.REGION_LABEL': 'Región',
    'GEOFENCES.CHANGE_REGION': 'Cambiar',
    'GEOFENCES.SELECT_REGION': 'Seleccionar región',
    'GEOFENCES.SEARCH_REGIONS': 'Buscar regiones...',
    'CLEANING.LABEL_EGGS': 'Huevos',
    'QUICK_PICKS.SNACK_FAILED_LOAD': 'Error al cargar las selecciones rápidas',
    'QUICK_PICKS.CONFIRM_DELETE_TITLE': 'Eliminar selección rápida',
    'QUICK_PICKS.CONFIRM_DELETE_MSG': '¿Eliminar "{{name}}" permanentemente?',
    'QUICK_PICKS.SNACK_FAILED_DELETE': 'Error al eliminar',
    'QUICK_PICKS.SNACK_DELETED': 'Selección rápida eliminada',
    'QUICK_PICKS.CONFIRM_REMOVE_TITLE': 'Quitar selección rápida',
    'QUICK_PICKS.CONFIRM_REMOVE_MSG': '¿Quitar "{{name}}"? Se eliminarán {{count}} alarma(s).',
    'QUICK_PICKS.SNACK_FAILED_REMOVE': 'Error al quitar',
    'QUICK_PICKS.SNACK_REMOVED': 'Selección rápida quitada -- {{count}} alarma(s) eliminada(s)',
    'QUICK_PICKS.CONFIRM_RESET_MSG': 'Se eliminarán todas las selecciones rápidas de admin y se recrearán los valores predeterminados.',
    'QUICK_PICKS.SNACK_FAILED_RESET': 'Error al restaurar los valores predeterminados',
    'QUICK_PICKS.SNACK_RESET': 'Valores predeterminados restaurados',
    'QUICK_PICKS.SNACK_FAILED_SAVE': 'Error al guardar la selección rápida',
    'QUICK_PICKS.SNACK_UPDATED': 'Selección rápida actualizada',
    'QUICK_PICKS.SNACK_CREATED_QP': 'Selección rápida creada',
    'QUICK_PICKS.APPLY_STATUS_CREATING': 'Creando {{count}} alarmas individuales...',
    'QUICK_PICKS.APPLY_STATUS_APPLYING': 'Aplicando selección rápida...',
    'QUICK_PICKS.SNACK_FAILED_APPLY': 'Error al aplicar la selección rápida',
    'QUICK_PICKS.SNACK_APPLIED': 'Selección rápida aplicada: {{count}} alarma(s) creada(s)',
    'QUICK_PICKS.TAB_OPTIONS': 'Opciones',
    'QUICK_PICKS.EXCLUDE_POKEMON': 'Excluir Pokemon específicos',
    'QUICK_PICKS.EXCLUDE_HINT': 'Omitir ciertos Pokemon de esta selección rápida.',
    'QUICK_PICKS.EXCLUDED_SUMMARY': '{{count}} Pokemon excluidos',
    'QUICK_PICKS.INDIVIDUAL_WARNING': 'Esto creará {{count}} filas de alarma individuales.',
    'QUICK_PICKS.NO_OPTIONS_HINT': 'Sin opciones adicionales. Cambia a la pestaña Entrega.',
    'QUICK_PICKS.TAB_DELIVERY': 'Entrega',
    'QUICK_PICKS.CLEAN_HINT': 'Elimina automáticamente la notificación después de expirar',
    'QUICK_PICKS.APPLYING': 'Aplicando...',
    'QUICK_PICKS.APPLY_WITH_COUNT': 'Aplicar ({{count}} alarmas)',
    'QUICK_PICKS.EDIT_DIALOG_TITLE': 'Editar selección rápida',
    'QUICK_PICKS.CREATE_DIALOG_TITLE': 'Crear selección rápida',
    'QUICK_PICKS.FIELD_NAME': 'Nombre',
    'QUICK_PICKS.FIELD_DESCRIPTION': 'Descripción',
    'QUICK_PICKS.FIELD_ICON': 'Icono',
    'QUICK_PICKS.FIELD_CATEGORY': 'Categoría',
    'QUICK_PICKS.FIELD_ALARM_TYPE': 'Tipo de alarma',
    'QUICK_PICKS.FIELD_SORT_ORDER': 'Orden',
    'QUICK_PICKS.FILTER_SETTINGS': 'Ajustes de filtro',
    'QUICK_PICKS.FIELD_POKEMON_ID': 'ID de Pokemon',
    'QUICK_PICKS.FIELD_EXCLUSIVE': 'Exclusivo',
    'QUICK_PICKS.FIELD_REWARD_TYPE': 'Tipo de recompensa',
    'QUICK_PICKS.FIELD_REWARD': 'Recompensa',
    'QUICK_PICKS.FIELD_SHINY': 'Shiny',
    'QUICK_PICKS.FIELD_GRUNT_TYPE': 'Tipo de recluta',
    'QUICK_PICKS.FIELD_LURE_ID': 'ID de señuelo',
    'QUICK_PICKS.FIELD_MOVE': 'Movimiento',
    'QUICK_PICKS.FIELD_EVOLUTION': 'Evolución',
    'AUTH.SITE_TITLE_DEFAULT': 'Alertas DM',
    'AUTH.AUTH_FAILED': 'Autenticación fallida',
    'AUTH.BACK_TO_LOGIN': 'Volver al inicio de sesión',
    'AUTH.ERR_DISCORD_FETCH': 'Error al obtener la información del usuario de Discord.',
    'AUTH.ERR_MISSING_CODE': 'No se recibió código de autorización de Discord.',
    'AUTH.ERR_TOKEN_EXCHANGE': 'Error al intercambiar el código de autorización con Discord.',
    'AUTH.ERR_NOT_REGISTERED': 'Tu cuenta no está registrada en Poracle.',
    'AUTH.ERR_GENERIC': 'Error de autenticación: {{error}}',
    'AUTH.ERR_NO_TOKEN': 'No se recibió token de autenticación.',
    'ADMIN.APPROVAL_DIALOG_TITLE': 'Revisar geofence',
    'ADMIN.APPROVAL_NAME': 'Nombre',
    'ADMIN.APPROVAL_GROUP': 'Grupo',
    'ADMIN.APPROVAL_SUBMITTED': 'Enviada',
    'ADMIN.APPROVAL_APPROVE': 'Aprobar',
    'ADMIN.APPROVAL_REJECT': 'Rechazar',
    'ADMIN.APPROVAL_PROMOTED_NAME': 'Nombre promovido',
    'ADMIN.APPROVAL_PROMOTED_NAME_PLACEHOLDER': 'Nombre para la geofence promovida',
    'ADMIN.APPROVAL_PROMOTED_NAME_HINT': 'Opcional. Por defecto, el nombre de visualización actual.',
    'ADMIN.APPROVAL_REJECT_REASON': 'Motivo del rechazo',
    'ADMIN.APPROVAL_REJECT_PLACEHOLDER': 'Explica por qué se rechaza esta geofence...',
    'ADMIN.USERS_DESC_FULL': 'Gestionar usuarios Discord registrados. <strong>Detenido</strong> = alertas pausadas o límite alcanzado. <strong>Bloqueado</strong> = bloqueado por admin.',
    'ADMIN.COLUMN_DISABLED_SINCE': 'Desactivado desde',
    'ADMIN.COLUMN_URL': 'URL',
    'ADMIN.COLUMN_DELEGATES': 'Delegados',
    'ADMIN.COLUMN_OWNER': 'Propietario',
    'ADMIN.COLUMN_REGION': 'Región',
    'ADMIN.COLUMN_POINTS': 'Puntos',
    'ADMIN.COLUMN_CREATED': 'Creado',
    'ADMIN.COLUMN_SUBMITTED': 'Enviado',
    'ADMIN.COLUMN_REVIEWED_BY': 'Revisado por',
    'ADMIN.TRY_ADJUSTING_FILTERS': 'Intenta ajustar tus filtros.',
    'ADMIN.NO_USERS_YET': 'Ningún usuario registrado aún.',
    'ADMIN.CONFIRM_DELETE_ALARMS': '¿Seguro que quieres eliminar TODAS las alarmas de "{{name}}"? Esta acción no se puede deshacer.',
    'ADMIN.CONFIRM_DELETE_USER': '¿Seguro que quieres eliminar permanentemente a "{{name}}"?',
    'ADMIN.SNACK_FAILED_IMPERSONATE': 'Error al suplantar al usuario',
    'ADMIN.SNACK_FAILED_LOAD_USERS': 'Error al cargar los usuarios',
    'ADMIN.WEBHOOKS_TITLE': 'Webhooks',
    'ADMIN.WEBHOOKS_DESC': 'Gestionar destinos webhook registrados.',
    'ADMIN.ADD_WEBHOOK': 'Añadir Webhook',
    'ADMIN.SEARCH_WEBHOOKS': 'Buscar webhooks',
    'ADMIN.FILTER_WEBHOOK_PLACEHOLDER': 'Filtrar por nombre o URL...',
    'ADMIN.CLICK_TO_COPY': 'Clic para copiar',
    'ADMIN.GLOBAL_ADMIN': 'admin global',
    'ADMIN.CONFIG_DELEGATE': 'delegado de config',
    'ADMIN.BLOCK_WEBHOOK': 'Bloquear webhook',
    'ADMIN.UNBLOCK_WEBHOOK': 'Desbloquear webhook',
    'ADMIN.MANAGE_ALARMS': 'Gestionar alarmas',
    'ADMIN.MANAGE_ALARMS_TOOLTIP': 'Gestionar alarmas de este webhook',
    'ADMIN.MANAGE_DELEGATES': 'Gestionar delegados',
    'ADMIN.DELETE_WEBHOOK': 'Eliminar webhook',
    'ADMIN.NO_WEBHOOKS': 'No se encontraron webhooks',
    'ADMIN.NO_WEBHOOKS_YET': 'No hay webhooks registrados.',
    'ADMIN.CONFIRM_DELETE_WEBHOOK': '¿Seguro que quieres eliminar permanentemente "{{name}}"?',
    'ADMIN.SNACK_FAILED_DELETE_WEBHOOK': 'Error al eliminar el webhook',
    'ADMIN.SNACK_WEBHOOK_DELETED': '"{{name}}" eliminado',
    'ADMIN.SNACK_URL_COPIED': 'URL copiada al portapapeles',
    'ADMIN.SNACK_FAILED_LOAD_WEBHOOKS': 'Error al cargar los webhooks',
    'ADMIN.SNACK_FAILED_SWITCH_WEBHOOK': 'Error al cambiar al contexto del webhook',
    'ADMIN.SNACK_FAILED_ADD_WEBHOOK': 'Error al añadir el webhook',
    'ADMIN.SNACK_WEBHOOK_ADDED': 'Webhook "{{name}}" añadido',
    'ADMIN.SNACK_FAILED_ADD_DELEGATE': 'Error al añadir el delegado',
    'ADMIN.SNACK_FAILED_LOAD_DELEGATES': 'Error al cargar los delegados',
    'ADMIN.SNACK_FAILED_REMOVE_DELEGATE': 'Error al eliminar el delegado',
    'ADMIN.MANAGE_DELEGATES_TITLE': 'Gestionar delegados',
    'ADMIN.DELEGATES_HINT': 'Los delegados pueden gestionar alarmas de este webhook.',
    'ADMIN.GLOBAL_ADMIN_TOOLTIP': 'Admin global (de la config de Poracle)',
    'ADMIN.CONFIG_DELEGATE_TOOLTIP': 'Delegado de la config de Poracle (solo lectura)',
    'ADMIN.REMOVE_DELEGATE': 'Eliminar delegado',
    'ADMIN.SEARCH_USER_LABEL': 'Buscar usuario por nombre o ID',
    'ADMIN.SEARCH_USER_PLACEHOLDER': 'Nombre o ID de usuario de Discord...',
    'ADMIN.WEBHOOK_NAME': 'Nombre',
    'ADMIN.WEBHOOK_NAME_PLACEHOLDER': 'ej. #pogo-alerts',
    'ADMIN.WEBHOOK_NAME_REQUIRED': 'El nombre es obligatorio',
    'ADMIN.WEBHOOK_URL': 'URL del Webhook',
    'ADMIN.WEBHOOK_URL_PLACEHOLDER': 'https://discord.com/api/webhooks/...',
    'ADMIN.WEBHOOK_URL_REQUIRED': 'La URL es obligatoria',
    'ADMIN.WEBHOOK_URL_INVALID': 'Debe ser una URL https:// válida',
    'ADMIN.MY_WEBHOOKS_TITLE': 'Mis Webhooks',
    'ADMIN.MY_WEBHOOKS_DESC': 'Webhooks de los que eres delegado.',
    'ADMIN.NO_WEBHOOKS_ASSIGNED': 'No hay webhooks asignados',
    'ADMIN.NO_WEBHOOKS_ASSIGNED_DESC': 'No has sido asignado como delegado de ningún webhook.',
    'ADMIN.GEOFENCES_TITLE': 'Geofences de usuarios',
    'ADMIN.GEOFENCES_DESC': 'Revisar envíos, gestionar geofences de usuarios y limpiar registros.',
    'ADMIN.GEO_STATUS_PENDING': 'Pendiente',
    'ADMIN.GEO_STATUS_APPROVED': 'Aprobada',
    'ADMIN.GEO_STATUS_REJECTED': 'Rechazada',
    'ADMIN.VIEW_CARD': 'Vista tarjeta (agrupada por región)',
    'ADMIN.VIEW_LIST': 'Vista lista (agrupada por región)',
    'ADMIN.VIEW_TABLE': 'Vista tabla (todas las geofences)',
    'ADMIN.VIEW_DETAILS': 'Ver detalles',
    'ADMIN.VIEW_GEOFENCE_DETAILS': 'Ver detalles de la geofence',
    'ADMIN.REVIEW': 'Revisar',
    'ADMIN.REVIEW_SUBMISSION': 'Revisar este envío',
    'ADMIN.DELETE_GEOFENCE': 'Eliminar geofence y limpiar',
    'ADMIN.NO_POLYGON_DATA': 'Sin datos de polígono',
    'ADMIN.POINTS': 'puntos',
    'ADMIN.CREATED': 'Creado',
    'ADMIN.SUBMITTED': 'Enviado',
    'ADMIN.REVIEWED_BY': 'Revisado por',
    'ADMIN.PROMOTED_AS': 'Promovida como:',
    'ADMIN.NO_REGION': 'Sin región',
    'ADMIN.NO_GEOFENCES': 'No hay geofences',
    'ADMIN.NO_PENDING_SUBMISSIONS': 'No hay envíos esperando revisión.',
    'ADMIN.NO_GEOFENCES_YET': 'No existen geofences creadas por usuarios aún.',
    'ADMIN.NO_GEOFENCES_STATUS': 'No hay geofences con este estado.',
    'ADMIN.CONFIRM_DELETE_GEOFENCE': '¿Eliminar permanentemente "{{name}}" (propietario: {{owner}})?',
    'ADMIN.ADMIN_DELETE_GEOFENCE': 'Admin: Eliminar geofence',
    'ADMIN.SNACK_FAILED_DELETE_GEOFENCE': 'Error al eliminar la geofence',
    'ADMIN.SNACK_GEOFENCE_DELETED': '"{{name}}" eliminada',
    'ADMIN.SNACK_FAILED_LOAD_GEOFENCES': 'Error al cargar las geofences',
    'ADMIN.SNACK_FAILED_APPROVE': 'Error al aprobar el envío',
    'ADMIN.SNACK_APPROVED': '"{{name}}" aprobada',
    'ADMIN.SNACK_FAILED_REJECT': 'Error al rechazar el envío',
    'ADMIN.SNACK_REJECTED': '"{{name}}" rechazada',
    'ADMIN.SERVERS_TITLE': 'Servidores Poracle',
    'ADMIN.SERVERS_DESC': 'Monitorear el estado de los servidores y reiniciar instancias de Poracle.',
    'ADMIN.REFRESH_STATUS': 'Actualizar estado del servidor',
    'ADMIN.RESTART_ALL': 'Reiniciar todos',
    'ADMIN.RESTART_ALL_TOOLTIP': 'Reiniciar todos los servidores Poracle',
    'ADMIN.RESTART_ALL_TITLE': 'Reiniciar todos los servidores Poracle',
    'ADMIN.CONFIRM_RESTART_ALL': 'Se reiniciarán TODOS los servidores Poracle. Los usuarios dejarán de recibir alertas brevemente.',
    'ADMIN.RESTART': 'Reiniciar',
    'ADMIN.RESTART_SERVER': 'Reiniciar este servidor',
    'ADMIN.RESTART_SERVER_TITLE': 'Reiniciar servidor Poracle',
    'ADMIN.CONFIRM_RESTART_SERVER': '¿Seguro que quieres reiniciar "{{name}}" ({{host}})?',
    'ADMIN.SERVER_ONLINE': 'En línea',
    'ADMIN.SERVER_OFFLINE': 'Fuera de línea',
    'ADMIN.CHECKED': 'Verificado',
    'ADMIN.NO_SERVERS': 'No se encontraron servidores Poracle',
    'ADMIN.NO_SERVERS_DESC': 'No hay instancias de servidor Poracle configuradas.',
    'ADMIN.SNACK_FAILED_RESTART_ALL': 'Error al reiniciar los servidores',
    'ADMIN.SNACK_ALL_RESTARTED': 'Todos los servidores reiniciados',
    'ADMIN.SNACK_FAILED_RESTART': 'Error al reiniciar "{{name}}"',
    'ADMIN.SNACK_RESTARTED': '"{{name}}" reiniciado',
    'ADMIN.SNACK_FAILED_LOAD_SERVERS': 'Error al cargar los servidores Poracle',
    'DIALOG.LOCATION_SAVE_ERROR': 'Error al actualizar la ubicación',
    'DIALOG.LOCATION_SAVE_SUCCESS': 'Ubicación actualizada correctamente',
    'DIALOG.LOCATION_GEO_UNSUPPORTED': 'La geolocalización no es compatible con tu navegador',
    'DIALOG.LOCATION_GEO_UNABLE': 'No se pudo obtener la ubicación',
    'DIALOG.LOCATION_GEO_DENIED': 'Permiso de ubicación denegado',
    'POKEMON_SELECTOR.GEN': 'Gen',
    'POKEMON_SELECTOR.TYPE': 'Tipo',
    'POKEMON_SELECTOR.LIVE': 'En vivo',
    'POKEMON_SELECTOR.SPAWNING': 'Apareciendo',
    'POKEMON_SELECTOR.SPECIES_ACTIVE': '{{count}} especies activas',
    'POKEMON_SELECTOR.SEARCH_LABEL': 'Buscar Pokemon',
    'POKEMON_SELECTOR.SEARCH_HINT': 'Escribe nombre o ID...',
    'POKEMON_SELECTOR.CURRENTLY_SPAWNING': 'Apareciendo actualmente',
    'TEMPLATE_SELECTOR.LABEL': 'Plantilla',
    'TEMPLATE_SELECTOR.DEFAULT': 'Predeterminada',
    'TEMPLATE_SELECTOR.TEMPLATE_NUM': 'Plantilla {{num}}',
    'TEMPLATE_SELECTOR.HINT': 'Formato del mensaje de notificación',
    'TEMPLATE_SELECTOR.HIDE_OPTIONS': 'Ocultar opciones',
    'TEMPLATE_SELECTOR.PREVIEW_OPTIONS': 'Opciones de vista previa',
    'TEMPLATE_SELECTOR.MAP_PREVIEW': 'Vista previa del mapa',
    'REGION_SELECTOR.ALL_REGIONS': 'Todas las regiones',
    'GYM_PICKER.SEARCH_LABEL': 'Buscar un gimnasio (opcional)',
    'GYM_PICKER.SEARCH_HINT': 'Escribe el nombre del gimnasio...',
    'GYM_PICKER.CLEAR_ARIA': 'Borrar selección de gimnasio',
    'DELIVERY_PREVIEW.AREAS_LABEL': 'Se enviarán notificaciones para estas zonas:',
    'DELIVERY_PREVIEW.NO_AREAS': 'No hay zonas configuradas.',
    'DELIVERY_PREVIEW.SET_UP_AREAS': 'Configurar zonas',
    'DELIVERY_PREVIEW.FIRST': 'primero.',
    'DELIVERY_PREVIEW.DISTANCE_LABEL': 'Notificaciones dentro de {{distance}} km de tu ubicación:',
    'DELIVERY_PREVIEW.MAP_ALT': 'Mapa del radio de distancia',
    'LOCATION_WARNING.TEXT': 'Sin ubicación establecida \u2014 el horario puede usar la zona horaria incorrecta',
    'LOCATION_WARNING.TOOLTIP': 'Las horas activas usan la ubicación del perfil para determinar la zona horaria. Sin ubicación establecida, el horario puede activarse a la hora incorrecta.',
    'ACTIVE_HOURS_CHIP.MANUAL_ONLY': 'Solo manual',
    'ACTIVE_HOURS_CHIP.NO_SCHEDULE': 'Sin horario establecido \u2014 el perfil funciona manualmente o siempre activo',
    'ALARM_INFO.PING_TOOLTIP': 'Ping: {{ping}}'
  },
  it: {
    'DASHBOARD.WEATHER_1_MIN_AGO': '1 min fa',
    'DASHBOARD.WEATHER_1_HR_AGO': '1 ora fa',
    'DASHBOARD.WEATHER_HRS_AGO': '{{count}} ore fa',
    'DASHBOARD.SWITCH_PROFILE_SUCCESS': 'Passato a "{{name}}"',
    'DASHBOARD.SWITCH_PROFILE_FAILED': 'Cambio profilo fallito',
    'ONBOARDING.ARIA_LABEL': 'Benvenuto onboarding',
    'POKEMON.ADD_POKEMON': 'Aggiungi Pokemon',
    'POKEMON.LABEL_FORM_ID': 'ID Forma',
    'POKEMON.FILTER_IV_CP_LEVEL': 'IV / CP / Livello',
    'POKEMON.FILTER_STATS_SECTION': 'Statistiche',
    'POKEMON.PVP_NONE_EDIT': 'Nessuna',
    'POKEMON.PVP_LITTLE_CUP_SHORT': 'Little Cup (500)',
    'POKEMON.PVP_GREAT_LEAGUE_SHORT': 'Great League (1500)',
    'POKEMON.PVP_ULTRA_LEAGUE_SHORT': 'Ultra League (2500)',
    'POKEMON.PVP_LEAGUE_SUFFIX': 'Lega',
    'POKEMON.PVP_RANK_RANGE': 'Rango {{best}}-{{worst}}',
    'POKEMON.PVP_BEST_RANK_HINT': 'es. 1',
    'POKEMON.PVP_WORST_RANK_HINT': 'es. 100',
    'ALARM.TAB_DELIVERY': 'Consegna',
    'ALARM.COMMON_SETTINGS': 'Impostazioni comuni',
    'RAIDS.LEVEL_MEGA': 'Mega',
    'RAIDS.ALL_RAIDS': 'Tutti i Raid',
    'RAIDS.ALL_LEVEL_RAIDS': 'Tutti i Raid {{level}}',
    'RAIDS.RAID_SUFFIX': 'Raid',
    'RAIDS.RAID_BOSS_NUM': 'Boss Raid #{{id}}',
    'RAIDS.POKEMON_SELECTED': '{{count}} Pokemon selezionati',
    'RAIDS.CLEAN_TAG': 'pulizia',
    'RAIDS.CLEAN_TOOLTIP': 'Eliminazione automatica dopo la scadenza',
    'RAIDS.SNACK_CREATED_COUNT': '{{count}} allarme/i creato/i',
    'RAIDS.SNACK_BULK_DELETED': '{{count}} allarmi eliminati',
    'RAIDS.SNACK_BULK_DISTANCE': 'Distanza aggiornata per {{count}} allarmi',
    'RAIDS.SNACK_ALL_DISTANCE': 'Tutte le distanze aggiornate',
    'RAIDS.SNACK_DELETED_ALL': 'Tutti gli allarmi raid e uova eliminati',
    'RAIDS.SNACK_FAILED_DELETE_ALL': 'Eliminazione allarmi fallita',
    'RAIDS.SNACK_FAILED_DISTANCE': 'Aggiornamento distanze fallito',
    'RAIDS.CONFIRM_DELETE_RAID_TITLE': 'Elimina Allarme Raid',
    'RAIDS.CONFIRM_DELETE_RAID_MSG': "Sei sicuro di voler eliminare l'allarme per {{name}}?",
    'RAIDS.CONFIRM_DELETE_EGG_TITLE': 'Elimina Allarme Uovo',
    'RAIDS.CONFIRM_DELETE_EGG_MSG': "Sei sicuro di voler eliminare l'allarme uovo {{name}}?",
    'RAIDS.CONFIRM_DELETE_ALL_TITLE': 'Elimina Tutti gli Allarmi Raid e Uova',
    'RAIDS.CONFIRM_DELETE_ALL_MSG': 'Sei sicuro di voler eliminare TUTTI gli allarmi raid e uova? Questa azione non può essere annullata.',
    'RAIDS.CONFIRM_BULK_DELETE_TITLE': 'Elimina Allarmi Selezionati',
    'RAIDS.CONFIRM_BULK_DELETE_MSG': 'Sei sicuro di voler eliminare {{count}} allarmi?',
    'RAIDS.CONFIRM_DELETE_SELECTED': 'Elimina selezionati',
    'QUESTS.TAB_SETTINGS': 'Impostazioni',
    'QUESTS.CLEAN_TAG': 'pulizia',
    'QUESTS.CLEAN_TOOLTIP': 'Eliminazione automatica dopo la scadenza',
    'QUESTS.SELECTION_COUNT': '{{count}} selezionati',
    'QUESTS.ANY_POKEMON_ENCOUNTER': 'Qualsiasi incontro Pokemon',
    'QUESTS.MEGA_ENERGY_SUFFIX': 'Mega Energia',
    'QUESTS.CANDY_SUFFIX': 'Caramelle',
    'QUESTS.STARDUST': 'Polvere di Stelle',
    'QUESTS.STARDUST_AMOUNT': '{{amount}} Polvere di Stelle',
    'QUESTS.REWARD_POKEMON': 'Pokemon',
    'QUESTS.REWARD_ITEM': 'Oggetto',
    'QUESTS.REWARD_MEGA_ENERGY': 'Mega Energia',
    'QUESTS.REWARD_CANDY': 'Caramelle',
    'QUESTS.REWARD_TYPE_PREFIX': 'Tipo Missione:',
    'QUESTS.REWARD_POKEMON_ENCOUNTER': 'Incontro Pokemon',
    'QUESTS.CONFIRM_DELETE_TITLE': 'Elimina Allarme Missione',
    'QUESTS.CONFIRM_DELETE_MSG': 'Sei sicuro di voler eliminare questo allarme missione?',
    'QUESTS.CONFIRM_DELETE_ALL_TITLE': 'Elimina Tutti gli Allarmi Missione',
    'QUESTS.CONFIRM_DELETE_ALL_MSG': 'Sei sicuro di voler eliminare TUTTI gli allarmi missione? Questa azione non può essere annullata.',
    'QUESTS.CONFIRM_BULK_DELETE_TITLE': 'Elimina Allarmi Selezionati',
    'QUESTS.CONFIRM_BULK_DELETE_MSG': 'Sei sicuro di voler eliminare {{count}} allarmi?',
    'QUESTS.SNACK_CREATED_COUNT': '{{count}} allarme/i missione creato/i',
    'QUESTS.SNACK_BULK_DELETED': '{{count}} allarmi eliminati',
    'QUESTS.SNACK_BULK_DISTANCE': 'Distanza aggiornata per {{count}} allarmi',
    'QUESTS.SNACK_ALL_DISTANCE': 'Tutte le distanze aggiornate',
    'QUESTS.SNACK_DELETED_ALL': 'Tutti gli allarmi missione eliminati',
    'QUESTS.SNACK_FAILED_DELETE_ALL': 'Eliminazione allarmi fallita',
    'QUESTS.SNACK_FAILED_DISTANCE': 'Aggiornamento distanze fallito',
    'INVASIONS.CLEAN_TAG': 'pulizia',
    'INVASIONS.CLEAN_TOOLTIP': 'Eliminazione automatica dopo la scadenza',
    'INVASIONS.POKESTOP_EVENT': 'Evento PokéStop',
    'INVASIONS.GENDER_ANY_LABEL': 'Qualsiasi genere',
    'INVASIONS.GENDER_LABEL': 'Genere',
    'INVASIONS.TAB_SETTINGS': 'Impostazioni',
    'INVASIONS.GENDER_FILTER_NA': 'Il filtro genere non si applica agli eventi PokéStop.',
    'INVASIONS.UNKNOWN_GRUNT': 'Recluta sconosciuta',
    'INVASIONS.SNACK_ALL_CREATED': 'Allarme tutte le invasioni creato',
    'INVASIONS.SNACK_CREATED_COUNT': '{{count}} allarme/i invasione creato/i',
    'INVASIONS.CONFIRM_DELETE_TITLE': 'Elimina Allarme Invasione',
    'INVASIONS.CONFIRM_DELETE_MSG': 'Sei sicuro di voler eliminare questo allarme invasione?',
    'INVASIONS.CONFIRM_DELETE_ALL_TITLE': 'Elimina Tutti gli Allarmi Invasione',
    'INVASIONS.CONFIRM_DELETE_ALL_MSG': 'Sei sicuro di voler eliminare TUTTI gli allarmi invasione? Questa azione non può essere annullata.',
    'INVASIONS.CONFIRM_BULK_DELETE_TITLE': 'Elimina Allarmi Selezionati',
    'INVASIONS.CONFIRM_BULK_DELETE_MSG': 'Sei sicuro di voler eliminare {{count}} allarmi?',
    'INVASIONS.SNACK_BULK_DELETED': '{{count}} allarmi eliminati',
    'INVASIONS.SNACK_BULK_DISTANCE': 'Distanza aggiornata per {{count}} allarmi',
    'INVASIONS.SNACK_ALL_DISTANCE': 'Tutte le distanze aggiornate',
    'INVASIONS.SNACK_DELETED_ALL': 'Tutti gli allarmi invasione eliminati',
    'INVASIONS.SNACK_FAILED_DELETE_ALL': 'Eliminazione allarmi fallita',
    'INVASIONS.SNACK_FAILED_DISTANCE': 'Aggiornamento distanze fallito',
    'AREAS.SEARCH_AREAS': 'Cerca aree',
    'PROFILES.SNACK_FAILED_UPDATE': 'Aggiornamento profilo fallito',
    'PROFILES.SNACK_UPDATED': 'Profilo rinominato in "{{name}}"',
    'PROFILES.SNACK_FAILED_SCHEDULE': 'Aggiornamento pianificazione fallito',
    'PROFILES.SNACK_SCHEDULE_UPDATED': 'Pianificazione aggiornata',
    'PROFILES.SNACK_EXPORTED': 'Backup "{{name}}" esportato',
    'PROFILES.SNACK_INVALID_BACKUP': 'Formato file di backup non valido',
    'PROFILES.SNACK_UNSUPPORTED_VERSION': 'Versione di backup non supportata',
    'PROFILES.SNACK_FAILED_LOAD': 'Caricamento panoramica profili fallito',
    'PROFILES.CONFIRM_DELETE_TITLE': 'Elimina Profilo',
    'PROFILES.CONFIRM_DELETE_MSG': 'Sei sicuro di voler eliminare il profilo "{{name}}" (#{{number}})? Tutti gli allarmi andranno persi.',
    'PROFILES.DUPLICATE_DIALOG_TITLE': 'Duplica Profilo',
    'PROFILES.DUPLICATE': 'Duplica',
    'PROFILES.DUPLICATE_DESC': 'Crea un nuovo profilo con tutti gli allarmi di {{name}}.',
    'PROFILES.NEW_PROFILE_NAME': 'Nuovo Nome Profilo',
    'PROFILES.IMPORT_DIALOG_TITLE': 'Importa Profilo',
    'PROFILES.IMPORT_DESC': 'Crea un nuovo profilo con tutti gli allarmi da questo backup.',
    'PROFILES.PROFILE_NUMBER': 'Numero Profilo',
    'PROFILES.SCHEDULE_TOOLTIP': 'Modifica pianificazione ore attive',
    'PROFILES.ACTIVE_HOURS_TITLE': 'Ore Attive',
    'PROFILES.ACTIVE_HOURS_DAYS': 'Giorni',
    'PROFILES.ACTIVE_HOURS_WEEKDAYS': 'Giorni feriali',
    'PROFILES.ACTIVE_HOURS_WEEKENDS': 'Fine settimana',
    'PROFILES.ACTIVE_HOURS_EVERY_DAY': 'Ogni giorno',
    'PROFILES.ACTIVE_HOURS_TIME': 'Orario',
    'PROFILES.ACTIVE_HOURS_HOUR': 'Ora',
    'PROFILES.ACTIVE_HOURS_MINUTE': 'Minuto',
    'PROFILES.ACTIVE_HOURS_ADD': 'Aggiungi',
    'PROFILES.ACTIVE_HOURS_ADD_TOOLTIP': 'Aggiungi regola di attivazione',
    'PROFILES.ACTIVE_HOURS_RULES': 'Regole',
    'PROFILES.ACTIVE_HOURS_NO_RULES': 'Nessuna regola di attivazione. Il profilo richiederà avvio manuale.',
    'PROFILES.ACTIVE_HOURS_REMOVE_RULE': 'Rimuovi regola',
    'PROFILES.ACTIVE_HOURS_WEEKLY_PREVIEW': 'Anteprima Settimanale',
    'PROFILES.ACTIVE_HOURS_CLEAR_ALL': 'Cancella Tutto',
    'GEOFENCES.CONFIRM_DELETE_TITLE': 'Elimina Geofence Personalizzata',
    'GEOFENCES.CONFIRM_DELETE_MSG': 'Sei sicuro di voler eliminare "{{name}}"?',
    'GEOFENCES.SNACK_FAILED_UPDATE': 'Aggiornamento geofence fallito',
    'GEOFENCES.SNACK_UPDATED': 'Geofence aggiornata',
    'GEOFENCES.SNACK_NO_EXPORT': 'Nessuna geofence da esportare',
    'GEOFENCES.SNACK_MIN_POINTS': 'Una geofence necessita di almeno 3 punti',
    'GEOFENCES.SNACK_IMPORTED': '{{count}} geofence importata/e',
    'GEOFENCES.SUBMIT_CONFIRM_TITLE': 'Invia Geofence per Revisione Pubblica',
    'GEOFENCES.SUBMIT_CONFIRM_TEXT': 'Invia per Revisione',
    'GEOFENCES.SUBMIT_CONFIRM_MSG': '"{{name}}" verrà inviata al team admin per la revisione.',
    'GEOFENCES.SNACK_FAILED_ACTIVATE': 'Attivazione geofence fallita',
    'GEOFENCES.SNACK_FAILED_DEACTIVATE': 'Disattivazione geofence fallita',
    'GEOFENCES.SNACK_EXPORTED': '{{count}} geofence esportata/e',
    'GEOFENCES.NAME_DIALOG_TITLE': 'Dai un Nome alla Geofence',
    'GEOFENCES.NAME_LABEL': 'Nome Geofence',
    'GEOFENCES.NAME_PLACEHOLDER': 'es. Il Mio Percorso del Parco',
    'GEOFENCES.NAME_WHITESPACE_ERROR': 'Il nome non può essere solo spazi',
    'GEOFENCES.NAME_INVALID_CHARS_ERROR': 'Solo lettere, numeri, spazi, trattini, apostrofi e parentesi sono consentiti',
    'GEOFENCES.REGION_LABEL': 'Regione',
    'GEOFENCES.CHANGE_REGION': 'Modifica',
    'GEOFENCES.SELECT_REGION': 'Seleziona Regione',
    'GEOFENCES.SEARCH_REGIONS': 'Cerca regioni...',
    'CLEANING.LABEL_EGGS': 'Uova',
    'QUICK_PICKS.SNACK_FAILED_LOAD': 'Caricamento selezioni rapide fallito',
    'QUICK_PICKS.CONFIRM_DELETE_TITLE': 'Elimina Selezione Rapida',
    'QUICK_PICKS.CONFIRM_DELETE_MSG': 'Eliminare definitivamente "{{name}}"?',
    'QUICK_PICKS.SNACK_FAILED_DELETE': 'Eliminazione fallita',
    'QUICK_PICKS.SNACK_DELETED': 'Selezione rapida eliminata',
    'QUICK_PICKS.CONFIRM_REMOVE_TITLE': 'Rimuovi Selezione Rapida',
    'QUICK_PICKS.CONFIRM_REMOVE_MSG': 'Rimuovere "{{name}}"? Verranno eliminati {{count}} allarme/i.',
    'QUICK_PICKS.SNACK_FAILED_REMOVE': 'Rimozione fallita',
    'QUICK_PICKS.SNACK_REMOVED': 'Selezione rapida rimossa -- {{count}} allarme/i eliminato/i',
    'QUICK_PICKS.CONFIRM_RESET_MSG': 'Verranno eliminate tutte le selezioni rapide admin e ricreati i valori predefiniti.',
    'QUICK_PICKS.SNACK_FAILED_RESET': 'Ripristino predefiniti fallito',
    'QUICK_PICKS.SNACK_RESET': 'Predefiniti ripristinati',
    'QUICK_PICKS.SNACK_FAILED_SAVE': 'Salvataggio selezione rapida fallito',
    'QUICK_PICKS.SNACK_UPDATED': 'Selezione rapida aggiornata',
    'QUICK_PICKS.SNACK_CREATED_QP': 'Selezione rapida creata',
    'QUICK_PICKS.APPLY_STATUS_CREATING': 'Creazione di {{count}} allarmi individuali...',
    'QUICK_PICKS.APPLY_STATUS_APPLYING': 'Applicazione selezione rapida...',
    'QUICK_PICKS.SNACK_FAILED_APPLY': 'Applicazione selezione rapida fallita',
    'QUICK_PICKS.SNACK_APPLIED': 'Selezione rapida applicata: {{count}} allarme/i creato/i',
    'QUICK_PICKS.TAB_OPTIONS': 'Opzioni',
    'QUICK_PICKS.EXCLUDE_POKEMON': 'Escludi Pokemon specifici',
    'QUICK_PICKS.EXCLUDE_HINT': 'Salta certi Pokemon da questa selezione rapida.',
    'QUICK_PICKS.EXCLUDED_SUMMARY': '{{count}} Pokemon esclusi',
    'QUICK_PICKS.INDIVIDUAL_WARNING': 'Questo creerà {{count}} righe di allarme individuali.',
    'QUICK_PICKS.NO_OPTIONS_HINT': 'Nessuna opzione aggiuntiva. Passa alla scheda Consegna.',
    'QUICK_PICKS.TAB_DELIVERY': 'Consegna',
    'QUICK_PICKS.CLEAN_HINT': 'Elimina automaticamente la notifica dopo la scadenza',
    'QUICK_PICKS.APPLYING': 'Applicazione...',
    'QUICK_PICKS.APPLY_WITH_COUNT': 'Applica ({{count}} allarmi)',
    'QUICK_PICKS.EDIT_DIALOG_TITLE': 'Modifica Selezione Rapida',
    'QUICK_PICKS.CREATE_DIALOG_TITLE': 'Crea Selezione Rapida',
    'QUICK_PICKS.FIELD_NAME': 'Nome',
    'QUICK_PICKS.FIELD_DESCRIPTION': 'Descrizione',
    'QUICK_PICKS.FIELD_ICON': 'Icona',
    'QUICK_PICKS.FIELD_CATEGORY': 'Categoria',
    'QUICK_PICKS.FIELD_ALARM_TYPE': 'Tipo di Allarme',
    'QUICK_PICKS.FIELD_SORT_ORDER': 'Ordinamento',
    'QUICK_PICKS.FILTER_SETTINGS': 'Impostazioni Filtro',
    'QUICK_PICKS.FIELD_POKEMON_ID': 'ID Pokemon',
    'QUICK_PICKS.FIELD_EXCLUSIVE': 'Esclusivo',
    'QUICK_PICKS.FIELD_REWARD_TYPE': 'Tipo Ricompensa',
    'QUICK_PICKS.FIELD_REWARD': 'Ricompensa',
    'QUICK_PICKS.FIELD_SHINY': 'Shiny',
    'QUICK_PICKS.FIELD_GRUNT_TYPE': 'Tipo Recluta',
    'QUICK_PICKS.FIELD_LURE_ID': 'ID Esca',
    'QUICK_PICKS.FIELD_MOVE': 'Mossa',
    'QUICK_PICKS.FIELD_EVOLUTION': 'Evoluzione',
    'AUTH.SITE_TITLE_DEFAULT': 'Avvisi DM',
    'AUTH.AUTH_FAILED': 'Autenticazione fallita',
    'AUTH.BACK_TO_LOGIN': "Torna all'accesso",
    'AUTH.ERR_DISCORD_FETCH': 'Recupero informazioni utente Discord fallito.',
    'AUTH.ERR_MISSING_CODE': 'Nessun codice di autorizzazione ricevuto da Discord.',
    'AUTH.ERR_TOKEN_EXCHANGE': 'Scambio del codice di autorizzazione con Discord fallito.',
    'AUTH.ERR_NOT_REGISTERED': 'Il tuo account non è registrato in Poracle.',
    'AUTH.ERR_GENERIC': 'Errore di autenticazione: {{error}}',
    'AUTH.ERR_NO_TOKEN': 'Nessun token di autenticazione ricevuto.',
    'ADMIN.APPROVAL_DIALOG_TITLE': 'Revisiona Geofence',
    'ADMIN.APPROVAL_NAME': 'Nome',
    'ADMIN.APPROVAL_GROUP': 'Gruppo',
    'ADMIN.APPROVAL_SUBMITTED': 'Inviata',
    'ADMIN.APPROVAL_APPROVE': 'Approva',
    'ADMIN.APPROVAL_REJECT': 'Rifiuta',
    'ADMIN.APPROVAL_PROMOTED_NAME': 'Nome promosso',
    'ADMIN.APPROVAL_PROMOTED_NAME_PLACEHOLDER': 'Nome per la geofence promossa',
    'ADMIN.APPROVAL_PROMOTED_NAME_HINT': 'Opzionale. Predefinito: il nome di visualizzazione attuale.',
    'ADMIN.APPROVAL_REJECT_REASON': 'Motivo del rifiuto',
    'ADMIN.APPROVAL_REJECT_PLACEHOLDER': 'Spiega perché questa geofence viene rifiutata...',
    'ADMIN.USERS_DESC_FULL': 'Gestisci gli utenti Discord registrati. <strong>Fermato</strong> = avvisi in pausa o limite raggiunto. <strong>Bloccato</strong> = bloccato dall\'admin.',
    'ADMIN.COLUMN_DISABLED_SINCE': 'Disabilitato dal',
    'ADMIN.COLUMN_URL': 'URL',
    'ADMIN.COLUMN_DELEGATES': 'Delegati',
    'ADMIN.COLUMN_OWNER': 'Proprietario',
    'ADMIN.COLUMN_REGION': 'Regione',
    'ADMIN.COLUMN_POINTS': 'Punti',
    'ADMIN.COLUMN_CREATED': 'Creato',
    'ADMIN.COLUMN_SUBMITTED': 'Inviato',
    'ADMIN.COLUMN_REVIEWED_BY': 'Revisionato da',
    'ADMIN.TRY_ADJUSTING_FILTERS': 'Prova a modificare i tuoi filtri.',
    'ADMIN.NO_USERS_YET': 'Nessun utente registrato ancora.',
    'ADMIN.CONFIRM_DELETE_ALARMS': 'Sei sicuro di voler eliminare TUTTI gli allarmi per "{{name}}"? Questa azione non può essere annullata.',
    'ADMIN.CONFIRM_DELETE_USER': 'Sei sicuro di voler eliminare definitivamente "{{name}}"?',
    'ADMIN.SNACK_FAILED_IMPERSONATE': "Impersonamento utente fallito",
    'ADMIN.SNACK_FAILED_LOAD_USERS': 'Caricamento utenti fallito',
    'ADMIN.WEBHOOKS_TITLE': 'Webhooks',
    'ADMIN.WEBHOOKS_DESC': 'Gestisci le destinazioni webhook registrate.',
    'ADMIN.ADD_WEBHOOK': 'Aggiungi Webhook',
    'ADMIN.SEARCH_WEBHOOKS': 'Cerca webhooks',
    'ADMIN.FILTER_WEBHOOK_PLACEHOLDER': 'Filtra per nome o URL...',
    'ADMIN.CLICK_TO_COPY': 'Clicca per copiare',
    'ADMIN.GLOBAL_ADMIN': 'admin globale',
    'ADMIN.CONFIG_DELEGATE': 'delegato config',
    'ADMIN.BLOCK_WEBHOOK': 'Blocca webhook',
    'ADMIN.UNBLOCK_WEBHOOK': 'Sblocca webhook',
    'ADMIN.MANAGE_ALARMS': 'Gestisci allarmi',
    'ADMIN.MANAGE_ALARMS_TOOLTIP': 'Gestisci allarmi per questo webhook',
    'ADMIN.MANAGE_DELEGATES': 'Gestisci delegati',
    'ADMIN.DELETE_WEBHOOK': 'Elimina webhook',
    'ADMIN.NO_WEBHOOKS': 'Nessun webhook trovato',
    'ADMIN.NO_WEBHOOKS_YET': 'Nessun webhook registrato.',
    'ADMIN.CONFIRM_DELETE_WEBHOOK': 'Sei sicuro di voler eliminare definitivamente "{{name}}"?',
    'ADMIN.SNACK_FAILED_DELETE_WEBHOOK': 'Eliminazione webhook fallita',
    'ADMIN.SNACK_WEBHOOK_DELETED': '"{{name}}" eliminato',
    'ADMIN.SNACK_URL_COPIED': 'URL copiata negli appunti',
    'ADMIN.SNACK_FAILED_LOAD_WEBHOOKS': 'Caricamento webhooks fallito',
    'ADMIN.SNACK_FAILED_SWITCH_WEBHOOK': 'Cambio al contesto webhook fallito',
    'ADMIN.SNACK_FAILED_ADD_WEBHOOK': 'Aggiunta webhook fallita',
    'ADMIN.SNACK_WEBHOOK_ADDED': 'Webhook "{{name}}" aggiunto',
    'ADMIN.SNACK_FAILED_ADD_DELEGATE': 'Aggiunta delegato fallita',
    'ADMIN.SNACK_FAILED_LOAD_DELEGATES': 'Caricamento delegati fallito',
    'ADMIN.SNACK_FAILED_REMOVE_DELEGATE': 'Rimozione delegato fallita',
    'ADMIN.MANAGE_DELEGATES_TITLE': 'Gestisci Delegati',
    'ADMIN.DELEGATES_HINT': 'I delegati possono gestire gli allarmi per questo webhook.',
    'ADMIN.GLOBAL_ADMIN_TOOLTIP': 'Admin globale (dalla config Poracle)',
    'ADMIN.CONFIG_DELEGATE_TOOLTIP': 'Delegato dalla config Poracle (sola lettura)',
    'ADMIN.REMOVE_DELEGATE': 'Rimuovi delegato',
    'ADMIN.SEARCH_USER_LABEL': 'Cerca utente per nome o ID',
    'ADMIN.SEARCH_USER_PLACEHOLDER': 'Nome o ID utente Discord...',
    'ADMIN.WEBHOOK_NAME': 'Nome',
    'ADMIN.WEBHOOK_NAME_PLACEHOLDER': 'es. #pogo-alerts',
    'ADMIN.WEBHOOK_NAME_REQUIRED': 'Il nome è obbligatorio',
    'ADMIN.WEBHOOK_URL': 'URL Webhook',
    'ADMIN.WEBHOOK_URL_PLACEHOLDER': 'https://discord.com/api/webhooks/...',
    'ADMIN.WEBHOOK_URL_REQUIRED': "L'URL è obbligatorio",
    'ADMIN.WEBHOOK_URL_INVALID': 'Deve essere un URL https:// valido',
    'ADMIN.MY_WEBHOOKS_TITLE': 'I Miei Webhooks',
    'ADMIN.MY_WEBHOOKS_DESC': 'Webhooks di cui sei delegato.',
    'ADMIN.NO_WEBHOOKS_ASSIGNED': 'Nessun webhook assegnato',
    'ADMIN.NO_WEBHOOKS_ASSIGNED_DESC': 'Non sei stato assegnato come delegato per nessun webhook.',
    'ADMIN.GEOFENCES_TITLE': 'Geofence Utenti',
    'ADMIN.GEOFENCES_DESC': 'Revisiona invii, gestisci geofence utenti e pulisci i record.',
    'ADMIN.GEO_STATUS_PENDING': 'In Attesa',
    'ADMIN.GEO_STATUS_APPROVED': 'Approvata',
    'ADMIN.GEO_STATUS_REJECTED': 'Rifiutata',
    'ADMIN.VIEW_CARD': 'Vista scheda (raggruppata per regione)',
    'ADMIN.VIEW_LIST': 'Vista lista (raggruppata per regione)',
    'ADMIN.VIEW_TABLE': 'Vista tabella (tutte le geofence)',
    'ADMIN.VIEW_DETAILS': 'Vedi dettagli',
    'ADMIN.VIEW_GEOFENCE_DETAILS': 'Vedi dettagli geofence',
    'ADMIN.REVIEW': 'Revisiona',
    'ADMIN.REVIEW_SUBMISSION': 'Revisiona questo invio',
    'ADMIN.DELETE_GEOFENCE': 'Elimina geofence e pulisci',
    'ADMIN.NO_POLYGON_DATA': 'Nessun dato poligono',
    'ADMIN.POINTS': 'punti',
    'ADMIN.CREATED': 'Creato',
    'ADMIN.SUBMITTED': 'Inviato',
    'ADMIN.REVIEWED_BY': 'Revisionato da',
    'ADMIN.PROMOTED_AS': 'Promossa come:',
    'ADMIN.NO_REGION': 'Nessuna Regione',
    'ADMIN.NO_GEOFENCES': 'Nessuna geofence',
    'ADMIN.NO_PENDING_SUBMISSIONS': 'Nessun invio in attesa di revisione.',
    'ADMIN.NO_GEOFENCES_YET': 'Nessuna geofence creata dagli utenti ancora.',
    'ADMIN.NO_GEOFENCES_STATUS': 'Nessuna geofence con questo stato.',
    'ADMIN.CONFIRM_DELETE_GEOFENCE': 'Eliminare definitivamente "{{name}}" (proprietario: {{owner}})?',
    'ADMIN.ADMIN_DELETE_GEOFENCE': 'Admin: Elimina Geofence',
    'ADMIN.SNACK_FAILED_DELETE_GEOFENCE': 'Eliminazione geofence fallita',
    'ADMIN.SNACK_GEOFENCE_DELETED': '"{{name}}" eliminata',
    'ADMIN.SNACK_FAILED_LOAD_GEOFENCES': 'Caricamento geofence fallito',
    'ADMIN.SNACK_FAILED_APPROVE': 'Approvazione invio fallita',
    'ADMIN.SNACK_APPROVED': '"{{name}}" approvata',
    'ADMIN.SNACK_FAILED_REJECT': 'Rifiuto invio fallito',
    'ADMIN.SNACK_REJECTED': '"{{name}}" rifiutata',
    'ADMIN.SERVERS_TITLE': 'Server Poracle',
    'ADMIN.SERVERS_DESC': 'Monitora lo stato dei server e riavvia le istanze Poracle.',
    'ADMIN.REFRESH_STATUS': 'Aggiorna stato server',
    'ADMIN.RESTART_ALL': 'Riavvia Tutti',
    'ADMIN.RESTART_ALL_TOOLTIP': 'Riavvia tutti i server Poracle',
    'ADMIN.RESTART_ALL_TITLE': 'Riavvia Tutti i Server Poracle',
    'ADMIN.CONFIRM_RESTART_ALL': 'Verranno riavviati TUTTI i server Poracle. Gli utenti smetteranno brevemente di ricevere avvisi.',
    'ADMIN.RESTART': 'Riavvia',
    'ADMIN.RESTART_SERVER': 'Riavvia questo server',
    'ADMIN.RESTART_SERVER_TITLE': 'Riavvia Server Poracle',
    'ADMIN.CONFIRM_RESTART_SERVER': 'Sei sicuro di voler riavviare "{{name}}" ({{host}})?',
    'ADMIN.SERVER_ONLINE': 'Online',
    'ADMIN.SERVER_OFFLINE': 'Offline',
    'ADMIN.CHECKED': 'Verificato',
    'ADMIN.NO_SERVERS': 'Nessun server Poracle trovato',
    'ADMIN.NO_SERVERS_DESC': 'Nessuna istanza server Poracle configurata.',
    'ADMIN.SNACK_FAILED_RESTART_ALL': 'Riavvio server fallito',
    'ADMIN.SNACK_ALL_RESTARTED': 'Tutti i server riavviati',
    'ADMIN.SNACK_FAILED_RESTART': 'Riavvio di "{{name}}" fallito',
    'ADMIN.SNACK_RESTARTED': '"{{name}}" riavviato',
    'ADMIN.SNACK_FAILED_LOAD_SERVERS': 'Caricamento server Poracle fallito',
    'DIALOG.LOCATION_SAVE_ERROR': 'Aggiornamento posizione fallito',
    'DIALOG.LOCATION_SAVE_SUCCESS': 'Posizione aggiornata con successo',
    'DIALOG.LOCATION_GEO_UNSUPPORTED': 'La geolocalizzazione non è supportata dal tuo browser',
    'DIALOG.LOCATION_GEO_UNABLE': 'Impossibile ottenere la posizione',
    'DIALOG.LOCATION_GEO_DENIED': 'Permesso di localizzazione negato',
    'POKEMON_SELECTOR.GEN': 'Gen',
    'POKEMON_SELECTOR.TYPE': 'Tipo',
    'POKEMON_SELECTOR.LIVE': 'Live',
    'POKEMON_SELECTOR.SPAWNING': 'In Spawn',
    'POKEMON_SELECTOR.SPECIES_ACTIVE': '{{count}} specie attive',
    'POKEMON_SELECTOR.SEARCH_LABEL': 'Cerca Pokemon',
    'POKEMON_SELECTOR.SEARCH_HINT': 'Digita nome o ID...',
    'POKEMON_SELECTOR.CURRENTLY_SPAWNING': 'Attualmente in spawn',
    'TEMPLATE_SELECTOR.LABEL': 'Modello',
    'TEMPLATE_SELECTOR.DEFAULT': 'Predefinito',
    'TEMPLATE_SELECTOR.TEMPLATE_NUM': 'Modello {{num}}',
    'TEMPLATE_SELECTOR.HINT': 'Formato del messaggio di notifica',
    'TEMPLATE_SELECTOR.HIDE_OPTIONS': 'Nascondi Opzioni',
    'TEMPLATE_SELECTOR.PREVIEW_OPTIONS': 'Opzioni Anteprima',
    'TEMPLATE_SELECTOR.MAP_PREVIEW': 'Anteprima Mappa',
    'REGION_SELECTOR.ALL_REGIONS': 'Tutte le Regioni',
    'GYM_PICKER.SEARCH_LABEL': 'Cerca una palestra (opzionale)',
    'GYM_PICKER.SEARCH_HINT': 'Digita il nome della palestra...',
    'GYM_PICKER.CLEAR_ARIA': 'Cancella selezione palestra',
    'DELIVERY_PREVIEW.AREAS_LABEL': 'Le notifiche verranno inviate per queste aree:',
    'DELIVERY_PREVIEW.NO_AREAS': 'Nessuna area configurata.',
    'DELIVERY_PREVIEW.SET_UP_AREAS': 'Configura le aree',
    'DELIVERY_PREVIEW.FIRST': 'prima.',
    'DELIVERY_PREVIEW.DISTANCE_LABEL': 'Notifiche entro {{distance}} km dalla tua posizione:',
    'DELIVERY_PREVIEW.MAP_ALT': 'Mappa raggio di distanza',
    'LOCATION_WARNING.TEXT': 'Nessuna posizione impostata \u2014 la pianificazione potrebbe usare il fuso orario sbagliato',
    'LOCATION_WARNING.TOOLTIP': "Le ore attive usano la posizione del profilo per determinare il fuso orario. Senza una posizione impostata, la pianificazione potrebbe attivarsi all'orario sbagliato.",
    'ACTIVE_HOURS_CHIP.MANUAL_ONLY': 'Solo manuale',
    'ACTIVE_HOURS_CHIP.NO_SCHEDULE': 'Nessuna pianificazione impostata \u2014 il profilo funziona manualmente o è sempre attivo',
    'ALARM_INFO.PING_TOOLTIP': 'Ping: {{ping}}'
  }
};

function buildMerged(enObj, existingObj, transMap, prefix) {
  const result = {};
  for (const key of Object.keys(enObj)) {
    const p = prefix ? prefix + '.' + key : key;
    if (typeof enObj[key] === 'object') {
      result[key] = buildMerged(enObj[key], existingObj && existingObj[key] || {}, transMap, p);
    } else {
      if (existingObj && existingObj[key] !== undefined) {
        result[key] = existingObj[key];
      } else if (transMap[p] !== undefined) {
        result[key] = transMap[p];
      } else {
        result[key] = enObj[key]; // fallback to English
      }
    }
  }
  return result;
}

const langs = ['de', 'fr', 'es', 'it'];
for (const lang of langs) {
  const existing = JSON.parse(fs.readFileSync(path.join(i18nDir, lang + '.json'), 'utf8'));
  const merged = buildMerged(en, existing, newTranslations[lang], '');

  // Verify
  let missing = 0;
  function check(enObj, mObj, p) {
    for (const k of Object.keys(enObj)) {
      const pp = p ? p + '.' + k : k;
      if (typeof enObj[k] === 'object') check(enObj[k], mObj[k] || {}, pp);
      else if (!mObj || mObj[k] === undefined) { missing++; console.log('MISSING in ' + lang + ': ' + pp); }
    }
  }
  check(en, merged, '');
  console.log(lang + ': missing=' + missing);

  fs.writeFileSync(path.join(i18nDir, lang + '.json'), JSON.stringify(merged, null, 2) + '\n', 'utf8');
  console.log(lang + '.json written');
}
